/**
 * BONEMAX course content. Facial structure, posture, debloat, fraudmaxxing.
 * Derived from rag_content/bonemax/*.md (the comprehensive coaching docs).
 * See ./courseContent.ts for the schema.
 */
import type { CourseModule } from './courseContent';

export const BONEMAX_COURSE: CourseModule = {
    maxxId: 'bonemax',
    accent: '#F59E0B',
    accentSoft: 'rgba(245, 158, 11, 0.10)',
    accentMid: 'rgba(245, 158, 11, 0.20)',
    caption: '14 chapters · 60 lessons · built for newcomers',
    chapters: [
        /* ── Ch 1 ──────────────────────────────────────────────────── */
        {
            id: 'foundations',
            number: 1,
            title: 'Bonemaxxing Foundations',
            subtitle: 'What can change, what cannot, and how to read the difference.',
            icon: 'leaf-outline',
            sections: [
                {
                    id: 'four-layers',
                    number: '1.1',
                    title: 'The Four Facial Layers',
                    subtitle: 'Bone, muscle, soft tissue, visual framing — work all four.',
                    icon: 'layers-outline',
                    eta: '3 min',
                    bullets: [
                        'Skeleton: maxilla, zygos, jaw, chin, brow, nose — mostly genetic',
                        'Muscle: masseters, neck, postural — strong/soft signal',
                        'Soft tissue: fat, water, fascia — daily variability',
                        'Visual framing: hair, brows, beard, lighting, camera',
                    ],
                },
                {
                    id: 'aesthetic-hierarchy',
                    number: '1.2',
                    title: 'Aesthetic Hierarchy',
                    subtitle: 'In rough order of impact for most faces.',
                    icon: 'list-outline',
                    eta: '2 min',
                    bullets: [
                        '1. Body fat low enough to expose structure',
                        '2. Posture and tongue position',
                        '3. Skin quality (light reflects cleanly)',
                        '4. Debloat / lymphatic flow',
                        '5. Strategic grooming and lighting',
                    ],
                },
                {
                    id: 'safe-bonemaxxing',
                    number: '1.3',
                    title: 'What Counts As Safe',
                    subtitle: 'Posture, sleep, nutrition, controlled chewing, grooming, fraudmaxxing.',
                    icon: 'shield-checkmark-outline',
                    eta: '2 min',
                    bullets: [
                        'Tongue posture, nasal breathing',
                        'Posture and neck training',
                        'Nutrition supporting bone density',
                        'Skin care, debloat, grooming',
                    ],
                },
                {
                    id: 'unsafe-bonemaxxing',
                    number: '1.4',
                    title: 'What Does NOT Belong',
                    subtitle: 'Anything that can injure your face is not bonemaxxing — it is injury.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Hitting or smashing facial bones',
                        'DIY jaw/chin pressure devices',
                        'Steroid creams off-label for "shrinking" features',
                        'MK-677 and similar research chemicals',
                        'Megadose supplement stacks',
                    ],
                },
                {
                    id: 'realistic-timeline',
                    number: '1.5',
                    title: 'Realistic Timelines',
                    subtitle: 'Adults: months for definition; years for tone.',
                    icon: 'hourglass-outline',
                    eta: '2 min',
                    bullets: [
                        'Debloat: visible same week',
                        'Body fat → jawline: 3–6 months of consistent cut',
                        'Posture / tongue posture: 6–12 months for adaptation',
                        'Bone changes in adults: orthognathic surgery only',
                    ],
                },
            ],
        },

        /* ── Ch 2 ──────────────────────────────────────────────────── */
        {
            id: 'maxilla',
            number: 2,
            title: 'Maxilla & Midface',
            subtitle: 'Forward-grown maxilla = sculpted, balanced midface.',
            icon: 'happy-outline',
            sections: [
                {
                    id: 'what-influences',
                    number: '2.1',
                    title: 'What Influences The Midface',
                    subtitle: 'Tongue posture, nasal breathing, dental alignment, posture.',
                    icon: 'options-outline',
                    eta: '2 min',
                    bullets: [
                        'Resting tongue posture (on palate)',
                        'Nasal breathing day and night',
                        'Head and neck posture',
                        'Dental alignment and bite',
                        'Most growth happens before sutures close in late teens',
                    ],
                },
                {
                    id: 'mewing',
                    number: '2.2',
                    title: 'Mewing',
                    subtitle: 'Whole tongue against palate. Gentle pressure, all day, never force.',
                    icon: 'fitness-outline',
                    eta: '3 min',
                    bullets: [
                        'Tip behind upper front teeth, not touching',
                        'Whole tongue suctioned flat to palate',
                        'Teeth lightly together, lips sealed, nasal breathing',
                        'Swallow with tongue pressing palate, not pushing teeth',
                        'Avoid: clenching, hard mewing, pushing teeth forward',
                    ],
                    body:
                        'Mewing works best in adolescents whose sutures are still malleable. Adults get smaller ' +
                        'real changes: better posture, reduced double chin from tongue tone, slightly firmer ' +
                        'submental area over 12+ months of consistent posture.',
                },
                {
                    id: 'nasal-breathing',
                    number: '2.3',
                    title: 'Nasal Breathing',
                    subtitle: 'Mouth breathing pulls head forward and undoes posture work overnight.',
                    icon: 'cloud-outline',
                    eta: '2 min',
                    bullets: [
                        'Confirm both nostrils breathe well — see ENT for chronic congestion',
                        'Treat allergies and sinus issues before tape or strips',
                        'Mouth tape only if cleared by clinician (not for sleep apnea)',
                        'Deviated septum + chronic snoring → sleep study',
                    ],
                },
                {
                    id: 'posture-midface',
                    number: '2.4',
                    title: 'Posture\'s Role',
                    subtitle: 'Forward-head posture rotates the cervical spine and tips chin down.',
                    icon: 'walk-outline',
                    eta: '2 min',
                    bullets: [
                        'Chin tucks: 3 sets of 10 daily',
                        'Wall posture hold: heels/butt/shoulders/head touching, 30–60s',
                        'Screen at eye level — biggest driver of forward-head posture',
                        'Lower screens = silently buried midface',
                    ],
                },
                {
                    id: 'midface-fraudmax',
                    number: '2.5',
                    title: 'Visual Boost',
                    subtitle: 'Contour and light to suggest midface projection.',
                    icon: 'sparkles-outline',
                    eta: '2 min',
                    bullets: [
                        'Light contour under cheek hollow',
                        'Highlight on upper cheek plane',
                        'Subtle blush above cheekbone',
                        'Hairstyle volume balanced — no narrow-on-top + narrow-midface combo',
                    ],
                },
            ],
        },

        /* ── Ch 3 ──────────────────────────────────────────────────── */
        {
            id: 'zygos',
            number: 3,
            title: 'Zygos & Cheekbones',
            subtitle: 'Top-three driver of facial harmony. Visibility, not bone, is what you change.',
            icon: 'eye-outline',
            sections: [
                {
                    id: 'what-makes-sharp',
                    number: '3.1',
                    title: 'What Makes Cheekbones Sharp',
                    subtitle: 'Bone width, low puffiness, skin tightness, body fat, lighting.',
                    icon: 'analytics-outline',
                    eta: '2 min',
                    bullets: [
                        'Underlying bone width and projection (genetic)',
                        'Low puffiness — water washes them out fast',
                        'Skin tightness over the zygomatic arch',
                        'Body fat low enough to expose bone shadow',
                    ],
                },
                {
                    id: 'safe-enhancement',
                    number: '3.2',
                    title: 'Safe Cheekbone Enhancement',
                    subtitle: 'Debloat, body composition, posture, skin, gentle massage.',
                    icon: 'checkmark-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Debloat: cut sodium, sleep elevated, hydrate',
                        '12–15% body fat exposes structure',
                        'Sunscreen + retinoid for tight skin (years compound)',
                        'Gentle gua sha 2–3 min, 3–5×/week',
                    ],
                },
                {
                    id: 'avoid',
                    number: '3.3',
                    title: 'What To Avoid',
                    subtitle: 'Aggressive techniques bruise tissue and inflame the area.',
                    icon: 'close-circle-outline',
                    eta: '1 min',
                    bullets: [
                        'No "bone smashing" — injury, not growth',
                        'No hammering devices',
                        'No hard pressure rolling',
                        'Bruising = the opposite of sharper',
                    ],
                },
                {
                    id: 'hollow-cheek',
                    number: '3.4',
                    title: 'Hollow-Cheek Illusion',
                    subtitle: 'Contour creates the shadow that bone alone might not project.',
                    icon: 'contrast-outline',
                    eta: '2 min',
                    bullets: [
                        'Matte bronzer right under the cheek hollow',
                        'Highlight on top of the cheekbone',
                        'Avoid shiny products in the lower cheek',
                        'Slight beard shadow / stubble deepens the contrast',
                    ],
                },
                {
                    id: 'lighting-zygos',
                    number: '3.5',
                    title: 'Lighting & Angles',
                    subtitle: 'Side-lit photos sculpt the cheekbone shadow naturally.',
                    icon: 'sunny-outline',
                    eta: '1 min',
                    bullets: [
                        'Side lighting at 45° = natural shadow',
                        '3/4 angle with chin slightly down',
                        'Avoid front flash — flattens everything',
                        'Golden hour = cheapest cheekbone upgrade',
                    ],
                },
            ],
        },

        /* ── Ch 4 ──────────────────────────────────────────────────── */
        {
            id: 'jawline',
            number: 4,
            title: 'Jawline Engineering',
            subtitle: 'Body fat + masseter + skin tightness + posture. Not bone, in adults.',
            icon: 'cut-outline',
            sections: [
                {
                    id: 'what-defines',
                    number: '4.1',
                    title: 'What Defines A Sharp Jawline',
                    subtitle: 'Mandible angle, masseter size, neck/face fat, skin tightness, posture.',
                    icon: 'options-outline',
                    eta: '2 min',
                    bullets: [
                        'Mandible angle and length (genetic)',
                        'Masseter muscle size (trainable, with care)',
                        'Neck and submental fat (diet + body comp)',
                        'Skin tightness along inferior border',
                        'Posture — forward-head buries the lower face',
                    ],
                },
                {
                    id: 'chewing-protocol',
                    number: '4.2',
                    title: 'Safe Chewing Protocol',
                    subtitle: 'Conservative because TMJ injuries are slow to heal.',
                    icon: 'restaurant-outline',
                    eta: '3 min',
                    bullets: [
                        'Mastic gum 5–10 min, 2–3×/week to start',
                        'Chew evenly both sides, alternate sides every minute',
                        'Stop if jaw clicks worsen, headaches, locking',
                        'Cap at 15 min × 4/week — more = square jaw not always wanted',
                    ],
                },
                {
                    id: 'tmj-safety',
                    number: '4.3',
                    title: 'TMJ Safety Rules',
                    subtitle: 'No daily overtraining. No clenching. No DIY pressure devices.',
                    icon: 'shield-outline',
                    eta: '2 min',
                    bullets: [
                        'No daily overtraining',
                        'No jaw clenching exercises',
                        'No "jaw exerciser" devices if any TMJ pain history',
                        'See a dentist or orthodontist if your bite feels off',
                    ],
                },
                {
                    id: 'jawline-fraudmax',
                    number: '4.4',
                    title: 'Jawline Fraudmaxxes',
                    subtitle: 'Beard, neckline, contour, angle.',
                    icon: 'sparkles-outline',
                    eta: '2 min',
                    bullets: [
                        'Beard or stubble lineup along the mandible',
                        'Neckline grooming creates "the edge"',
                        'Light contour under jaw shadow',
                        'Camera slightly below eye level',
                    ],
                },
                {
                    id: 'underlying-drivers',
                    number: '4.5',
                    title: 'Underlying Drivers Beat Tricks',
                    subtitle: 'Cut to 12–15%, fix posture, then layer in masseter + grooming.',
                    icon: 'trending-down-outline',
                    eta: '1 min',
                    bullets: [
                        '18% body fat + forward-head = no jawline regardless of effort',
                        'Body composition first',
                        'Posture second',
                        'Masseter and grooming third',
                    ],
                },
            ],
        },

        /* ── Ch 5 ──────────────────────────────────────────────────── */
        {
            id: 'chin',
            number: 5,
            title: 'Chin & Lower Third',
            subtitle: 'Sets the lower-face balance. Mostly visibility, not bone.',
            icon: 'arrow-down-outline',
            sections: [
                {
                    id: 'chin-drivers',
                    number: '5.1',
                    title: 'What Drives Chin Appearance',
                    subtitle: 'Bone projection, dental bite, submental fat, posture.',
                    icon: 'analytics-outline',
                    eta: '2 min',
                    bullets: [
                        'Bone projection (surgical change only in adults)',
                        'Dental bite — overbite or recessed jaw',
                        'Submental fat — biggest day-to-day variable',
                        'Tongue and neck posture',
                    ],
                },
                {
                    id: 'safe-improvement',
                    number: '5.2',
                    title: 'Safe Improvement',
                    subtitle: 'Posture, tongue posture, neck training, body comp.',
                    icon: 'checkmark-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Chin tucks + tongue posture',
                        'Neck training reduces "soft under-chin" look',
                        'Body comp: most "weak chins" are 17–20% body fat hiding mandible',
                        'Orthodontic eval if bite genuinely sits behind upper teeth',
                    ],
                },
                {
                    id: 'chin-fraudmax',
                    number: '5.3',
                    title: 'Chin Fraudmaxxes',
                    subtitle: 'Contour, highlight, beard, angle.',
                    icon: 'sparkles-outline',
                    eta: '1 min',
                    bullets: [
                        'Light contour just under the lower lip',
                        'Highlight center of chin',
                        'Beard or stubble shaping along chin point',
                        'Camera below eye level adds projection',
                    ],
                },
                {
                    id: 'never-do',
                    number: '5.4',
                    title: 'What Not To Do',
                    subtitle: 'Pressure devices, smashing, clenching protocols.',
                    icon: 'close-circle-outline',
                    eta: '1 min',
                    bullets: [
                        'No "chin smashing"',
                        'No DIY pressure devices',
                        'No clenching routines',
                        'Chin is structurally fixed in adults — improve how it READS',
                    ],
                },
            ],
        },

        /* ── Ch 6 ──────────────────────────────────────────────────── */
        {
            id: 'neck-posture',
            number: 6,
            title: 'Neck, Hyoid & Posture',
            subtitle: 'Strong neck + clean posture > almost any single facial intervention.',
            icon: 'man-outline',
            sections: [
                {
                    id: 'why-neck-matters',
                    number: '6.1',
                    title: 'Why The Neck Matters',
                    subtitle: 'Posture sets the angle between jaw and clavicle — that IS the jawline.',
                    icon: 'eye-outline',
                    eta: '2 min',
                    bullets: [
                        'Strong traps + neck = head proportionate to frame',
                        'Forward-head posture hides the jawline',
                        'Hyoid position affects under-chin definition',
                        'Weak neck on muscular body looks "pinhead"',
                    ],
                },
                {
                    id: 'posture-drill',
                    number: '6.2',
                    title: 'Daily Posture Drill',
                    subtitle: 'Five exercises, ten minutes, every day.',
                    icon: 'fitness-outline',
                    eta: '3 min',
                    bullets: [
                        'Chin tucks: 3 sets of 10',
                        'Wall posture hold: 30–60s, 1–2× daily',
                        'Shoulder retractions: 2 sets of 10, hold 5s',
                        'Thoracic extension on foam roller: 1–2 min',
                        'Deep nasal breathing: 5 min/day',
                    ],
                },
                {
                    id: 'neck-training',
                    number: '6.3',
                    title: 'Neck Training Protocol',
                    subtitle: 'Light, slow, controlled. Small joints, no margin for jerky reps.',
                    icon: 'barbell-outline',
                    eta: '2 min',
                    bullets: [
                        'Neck curls: 2×15',
                        'Neck extensions: 2×15',
                        'Side isometrics: 10s × 3 each side',
                        'Trap shrugs: 3×12–15, controlled tempo',
                        '2–3×/week, stop if dizzy or numb',
                    ],
                },
                {
                    id: 'under-chin',
                    number: '6.4',
                    title: 'Under-Chin Definition',
                    subtitle: 'Tongue + posture + body comp + debloat.',
                    icon: 'arrow-down-outline',
                    eta: '1 min',
                    bullets: [
                        'Tongue-on-palate posture',
                        'Chin tucks',
                        'Lower body fat',
                        'Debloat routine before photos',
                    ],
                },
                {
                    id: 'photo-posture',
                    number: '6.5',
                    title: 'Photo Posture',
                    subtitle: 'The pose that makes the same face read 2 points higher.',
                    icon: 'camera-outline',
                    eta: '2 min',
                    bullets: [
                        'Neck long, ears stacked over shoulders',
                        'Chin slightly forward and down',
                        'Tongue on palate (firms the under-chin)',
                        'Slight squint adds tension to the eye area',
                    ],
                },
            ],
        },

        /* ── Ch 7 ──────────────────────────────────────────────────── */
        {
            id: 'eye-brow',
            number: 7,
            title: 'Brow Ridge & Eye Area',
            subtitle: 'Ridge is genetic. The eye area changes daily — that\'s the leverage.',
            icon: 'eye-outline',
            sections: [
                {
                    id: 'what-makes-strong',
                    number: '7.1',
                    title: 'What Makes Eyes Read Strong',
                    subtitle: 'Tight under-eye, defined orbital shadow, clean brow.',
                    icon: 'analytics-outline',
                    eta: '2 min',
                    bullets: [
                        'Tight, even under-eye tone (no purple/grey)',
                        'Defined orbital shadow (not puffy, not sunken)',
                        'Clean brow shape framing the eye',
                        'Brow ridge close to lash line + slight squint = "hunter eyes"',
                    ],
                },
                {
                    id: 'safe-enhancement-eye',
                    number: '7.2',
                    title: 'Safe Eye Enhancement',
                    subtitle: 'Sleep, allergies, SPF, caffeine serum, retinoid.',
                    icon: 'checkmark-circle-outline',
                    eta: '3 min',
                    bullets: [
                        'Sleep 7–9 h consistent — biggest under-eye variable',
                        'Treat chronic allergies (cause of dark under-eyes)',
                        'Sunscreen daily — UV ages eye area first',
                        'Caffeine serum vasoconstricts under-eye in 10–20 min',
                        'Cold compress 30–60s morning',
                    ],
                },
                {
                    id: 'eye-never-do',
                    number: '7.3',
                    title: 'What Not To Do',
                    subtitle: 'Brow ridge area is fragile. Treat carefully.',
                    icon: 'close-circle-outline',
                    eta: '1 min',
                    bullets: [
                        'No hitting/smashing brow ridge',
                        'No hydrocortisone off-label on eye area',
                        'No aggressive tugging',
                        'No daily harsh exfoliation under the eye',
                    ],
                },
                {
                    id: 'brow-fraudmax',
                    number: '7.4',
                    title: 'Brow Fraudmaxxes',
                    subtitle: 'Brow shape, density, color frame the eye.',
                    icon: 'sparkles-outline',
                    eta: '1 min',
                    bullets: [
                        'Brow tinting evens color and adds visual density',
                        'Brow gel sets hairs in a slight upward sweep',
                        'Slight darkening at outer brow extends the eye',
                        'Matte shadow in orbital crease deepens socket',
                    ],
                },
            ],
        },

        /* ── Ch 8 ──────────────────────────────────────────────────── */
        {
            id: 'debloat',
            number: 8,
            title: 'Debloat & Fascia',
            subtitle: 'Most "I look bad today" days are fluid. Reduce it overnight.',
            icon: 'snow-outline',
            sections: [
                {
                    id: 'why-puffy',
                    number: '8.1',
                    title: 'What Causes Puffiness',
                    subtitle: 'Sodium, alcohol, sleep, allergies, lymphatic stagnation.',
                    icon: 'water-outline',
                    eta: '2 min',
                    bullets: [
                        'High sodium dinner — face holds water 12–16 h',
                        'Alcohol disrupts deep sleep + dehydrates',
                        'Allergies puff under-eyes (histamine)',
                        'Sleeping flat lets fluid pool — head-elevated helps',
                    ],
                },
                {
                    id: 'daily-protocol',
                    number: '8.2',
                    title: 'Daily Debloat Protocol',
                    subtitle: 'Cold splash, hydration, walk, gentle lymph.',
                    icon: 'leaf-outline',
                    eta: '2 min',
                    bullets: [
                        'Cold splash 30–60s morning',
                        '2–3 L water/day (counterintuitive but real)',
                        '10–15 min morning walk activates lymph',
                        'Light lymph: cheek → ear → neck → collarbone',
                    ],
                },
                {
                    id: 'lymph-drainage',
                    number: '8.3',
                    title: 'Lymphatic Drainage',
                    subtitle: 'Light pressure, downward only, finishes at collarbone.',
                    icon: 'arrow-down-outline',
                    eta: '2 min',
                    bullets: [
                        'Drain DOWNWARD only (toward collarbone)',
                        'Light pressure — moving lymph just under the skin',
                        'Behind ears → sides of neck → collarbone',
                        'Skip if skin irritation or active acne flare',
                    ],
                },
                {
                    id: 'gua-sha-safety',
                    number: '8.4',
                    title: 'Gua Sha Safety',
                    subtitle: 'Light pressure only. Bruising = inflamed = puffier.',
                    icon: 'shield-outline',
                    eta: '2 min',
                    bullets: [
                        'Light pressure — never lasting redness',
                        '2–3 min per session, 3–5×/week',
                        'Use slip product (oil or moisturizer)',
                        'Outward and downward, never against muscle direction',
                    ],
                },
                {
                    id: 'pre-photo',
                    number: '8.5',
                    title: 'Pre-Photo 24h Prep',
                    subtitle: 'When you need to look your best on a specific day.',
                    icon: 'camera-outline',
                    eta: '2 min',
                    bullets: [
                        'Cap sodium under 2g for the day',
                        'No alcohol; no late high-carb dinner',
                        '8+ h sleep, head elevated',
                        'Morning: cold splash → light gua sha → caffeine serum → walk',
                    ],
                },
            ],
        },

        /* ── Ch 9 ──────────────────────────────────────────────────── */
        {
            id: 'nutrition',
            number: 9,
            title: 'Bone Nutrition & Micronutrients',
            subtitle: 'Bone is metabolically active. Get the basics right; skip megadoses.',
            icon: 'nutrition-outline',
            sections: [
                {
                    id: 'core-nutrients',
                    number: '9.1',
                    title: 'Core Nutrients',
                    subtitle: 'Protein, vitamin D, calcium, magnesium, vitamin K2, zinc.',
                    icon: 'flask-outline',
                    eta: '3 min',
                    bullets: [
                        'Protein: 0.8–1 g/lb — bone is 1/3 protein matrix',
                        'Vitamin D: 1000–2000 IU/day if sun is low',
                        'Calcium: 1000–1200 mg/day, ideally from food',
                        'Magnesium: 300–400 mg/day, glycinate or citrate',
                        'Vitamin K2 (MK-7): 90–180 mcg/day',
                    ],
                },
                {
                    id: 'food-sources',
                    number: '9.2',
                    title: 'Food-First Sources',
                    subtitle: 'Real food beats most supplement stacks.',
                    icon: 'restaurant-outline',
                    eta: '2 min',
                    bullets: [
                        'Dairy (or fortified alternatives) — calcium, protein, D',
                        'Eggs — vitamin D, choline, complete protein',
                        'Fatty fish — vitamin D, K2, omega-3',
                        'Leafy greens — vitamin K, magnesium, calcium',
                        'Nuts and seeds — magnesium, healthy fats',
                    ],
                },
                {
                    id: 'supplement-tier',
                    number: '9.3',
                    title: 'Supplement Hierarchy',
                    subtitle: 'If you supplement, do it in this order.',
                    icon: 'medal-outline',
                    eta: '2 min',
                    bullets: [
                        '1. Vitamin D if blood level <30 ng/mL',
                        '2. Magnesium glycinate at night',
                        '3. K2 (MK-7) if also on calcium or D supplements',
                        '4. Whey or plant protein if dietary target hard to hit',
                    ],
                },
                {
                    id: 'avoid',
                    number: '9.4',
                    title: 'What To Avoid',
                    subtitle: 'Research chemicals, megadoses, hormone-manipulation supplements.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'MK-677 — research chemical, real cardiovascular risks',
                        'Megadose single nutrients without bloodwork',
                        'Stacking 10+ supplements (interactions multiply)',
                        '"Facial growth" hormone supplements in adults — cope',
                    ],
                },
            ],
        },

        /* ── Ch 10 ─────────────────────────────────────────────────── */
        {
            id: 'sleep-recovery',
            number: 10,
            title: 'Sleep, IGF-1 & Recovery',
            subtitle: 'The face you see is mostly a sleep diagnostic.',
            icon: 'bed-outline',
            sections: [
                {
                    id: 'why-sleep',
                    number: '10.1',
                    title: 'Why Sleep Drives Face',
                    subtitle: 'GH pulses, IGF-1, cortisol, lymphatic clearance — all happen at night.',
                    icon: 'moon-outline',
                    eta: '2 min',
                    bullets: [
                        'GH pulses during deep sleep support skin and bone repair',
                        'IGF-1 stays healthy with adequate sleep + protein',
                        'Cortisol drops overnight; short sleep keeps it elevated',
                        'Skin barrier repair peaks in second half of night',
                    ],
                },
                {
                    id: 'sleepmaxxing',
                    number: '10.2',
                    title: 'Sleepmaxxing For The Face',
                    subtitle: 'Specific tactics that visibly change next-morning skin.',
                    icon: 'star-outline',
                    eta: '2 min',
                    bullets: [
                        '7–9 h, consistent ±30 min',
                        'Cool room (65–68°F) — face fluid drains better',
                        'Nasal breathing all night',
                        'No alcohol within 4 h of bed',
                    ],
                },
                {
                    id: 'training-structure',
                    number: '10.3',
                    title: 'Training For Structure',
                    subtitle: 'Resistance training raises IGF-1 and supports bone density.',
                    icon: 'barbell-outline',
                    eta: '2 min',
                    bullets: [
                        '3–4 strength sessions per week',
                        'Compound lifts: squat, deadlift, bench, row, OHP',
                        'Neck and trap work 2×/week',
                        'Sprint or conditioning 1–2×/week',
                    ],
                },
                {
                    id: 'recovery-math',
                    number: '10.4',
                    title: 'Recovery Math',
                    subtitle: 'Calories at maintenance, protein hit, sleep nailed.',
                    icon: 'calculator-outline',
                    eta: '2 min',
                    bullets: [
                        'Calories at maintenance or slight surplus if growing',
                        'Protein 0.8–1 g/lb',
                        'Hydration 2–3 L (more with training/heat)',
                        '1–2 full rest days per week',
                    ],
                },
            ],
        },

        /* ── Ch 11 ─────────────────────────────────────────────────── */
        {
            id: 'fraudmaxxing',
            number: 11,
            title: 'Fraudmaxxing',
            subtitle: 'Visual enhancement without structural change. Treat as a serious skill.',
            icon: 'sparkles-outline',
            sections: [
                {
                    id: 'what-counts',
                    number: '11.1',
                    title: 'What Counts',
                    subtitle: 'Makeup, grooming, lighting, posing, styling. Reversible, ethical.',
                    icon: 'checkmark-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Subtle contouring (cream or matte powder, light hand)',
                        'Strategic highlighter placement',
                        'Brow shaping and tinting',
                        'Beard / stubble lineup, hairstyle, photo angle',
                    ],
                },
                {
                    id: 'cheekbone-fraudmax',
                    number: '11.2',
                    title: 'Cheekbone Fraudmaxxes',
                    subtitle: 'Contour + highlight + matte lower cheek.',
                    icon: 'eye-outline',
                    eta: '2 min',
                    bullets: [
                        'Matte bronzer right under the cheek hollow',
                        'Highlighter on top of cheekbone (subtle satin)',
                        'Blush above cheekbone for flushed read',
                        'Matte finish on lower cheek so it doesn\'t compete',
                    ],
                },
                {
                    id: 'eye-fraudmax',
                    number: '11.3',
                    title: 'Eye Area Fraudmaxxes',
                    subtitle: 'Eyeliner, brow gel, concealer, caffeine serum.',
                    icon: 'eye-outline',
                    eta: '1 min',
                    bullets: [
                        'Eyeliner on upper lash line deepens orbital contrast',
                        'Brow gel + tint = framed, intentional brows',
                        'Color corrector + concealer for under-eyes',
                        'Caffeine serum 30 min before photos',
                    ],
                },
                {
                    id: 'jaw-fraudmax',
                    number: '11.4',
                    title: 'Jaw Fraudmaxxes',
                    subtitle: 'Beard, neckline, contour, debloat, angle.',
                    icon: 'cut-outline',
                    eta: '1 min',
                    bullets: [
                        'Beard or stubble shaping along mandible angle',
                        'Neckline cleanup (sharp boundary between hair and skin)',
                        'Light contour right under jaw shadow',
                        'Lower-face debloat 24 h before photos',
                    ],
                },
                {
                    id: 'hair-fraudmax',
                    number: '11.5',
                    title: 'Hair Fraudmaxxes',
                    subtitle: 'Volume on top, balanced sides, side profile matters.',
                    icon: 'cut-outline',
                    eta: '1 min',
                    bullets: [
                        'Volume on top to balance a wide face',
                        'Flatter sides slim a round face',
                        'Side profile silhouette matters more than people think',
                        'Don\'t fight your face shape with trend cuts',
                    ],
                },
            ],
        },

        /* ── Ch 12 ─────────────────────────────────────────────────── */
        {
            id: 'photo-camera',
            number: 12,
            title: 'Photo & Camera Maxxing',
            subtitle: 'Most "transformations" online are 80% better photography.',
            icon: 'camera-outline',
            sections: [
                {
                    id: 'lighting',
                    number: '12.1',
                    title: 'Lighting',
                    subtitle: 'Natural diffuse light, side lighting at 45°, golden hour.',
                    icon: 'sunny-outline',
                    eta: '3 min',
                    bullets: [
                        'Natural diffuse light (overcast / window) — most flattering',
                        'Side lighting at 45° sculpts cheekbones and jaw',
                        'Golden hour (last hour before sunset) — warm and forgiving',
                        'Avoid: overhead lighting (eye shadows), front flash (flat)',
                    ],
                },
                {
                    id: 'angles',
                    number: '12.2',
                    title: 'Angles',
                    subtitle: 'Above eye for soft, below for jaw, 3/4 for cheekbone.',
                    icon: 'aperture-outline',
                    eta: '2 min',
                    bullets: [
                        'Slightly above eye level: softer face, larger eyes',
                        'Slightly below eye level: stronger jaw, projected chin',
                        '3/4 angle (~30° rotation): activates cheekbone shadow',
                        'Side profile: shows ogee curve, jaw projection — most diagnostic',
                    ],
                },
                {
                    id: 'lens-distance',
                    number: '12.3',
                    title: 'Lens & Distance',
                    subtitle: 'Phone front cameras are wide-angle. They distort.',
                    icon: 'phone-portrait-outline',
                    eta: '2 min',
                    bullets: [
                        'Phone front cameras distort when held close',
                        'Back up to arm\'s length minimum',
                        '50mm-equivalent or longer = most natural facial proportions',
                        'For serious selfies: ask someone to use the back camera',
                    ],
                },
                {
                    id: 'pre-photo',
                    number: '12.4',
                    title: 'Pre-Photo Routine',
                    subtitle: 'Sleep, low sodium, hydration, cold splash, walk.',
                    icon: 'leaf-outline',
                    eta: '2 min',
                    bullets: [
                        '8+ h sleep night before',
                        'Low sodium for 24 h',
                        'Cold splash + light gua sha morning of',
                        'Caffeine eye serum 30 min before',
                        'Light meal 90 min before — full not bloated',
                    ],
                },
                {
                    id: 'wreckers',
                    number: '12.5',
                    title: 'What Wrecks Photos',
                    subtitle: 'The mistakes nobody tells you about.',
                    icon: 'close-circle-outline',
                    eta: '1 min',
                    bullets: [
                        'Phone held below the chin (under-chin shadow)',
                        'Phone above the head (childlike, loses jaw)',
                        'Smiling fake-wide (cheek puffiness)',
                        'Plain wall behind (no depth, face looks flat)',
                    ],
                },
            ],
        },

        /* ── Ch 13 ─────────────────────────────────────────────────── */
        {
            id: 'safety',
            number: 13,
            title: 'Safety Rules & Red Flags',
            subtitle: 'When to stop, when to see a professional.',
            icon: 'shield-outline',
            sections: [
                {
                    id: 'stop-immediately',
                    number: '13.1',
                    title: 'Stop Immediately If',
                    subtitle: 'Symptoms that should end any protocol the same day.',
                    icon: 'warning-outline',
                    eta: '2 min',
                    bullets: [
                        'Jaw clicking gets worse, or starts',
                        'TMJ pain, especially after starting chewing or jaw exercises',
                        'Headaches triggered by chewing',
                        'Numbness, tingling, persistent swelling',
                        'Bruising that doesn\'t fade in 3–4 days',
                    ],
                },
                {
                    id: 'see-pro',
                    number: '13.2',
                    title: 'See A Professional For',
                    subtitle: 'The signals that beat any home routine.',
                    icon: 'medical-outline',
                    eta: '2 min',
                    bullets: [
                        'Bite that doesn\'t close evenly — orthodontist',
                        'Chronic mouth breathing or sleep apnea symptoms — ENT',
                        'Snoring + waking gasping → suspect OSA',
                        'Persistent skin redness, acne, pigmentation — derm',
                    ],
                },
                {
                    id: 'never-do',
                    number: '13.3',
                    title: 'Never Do',
                    subtitle: 'The list that should be on a sticker on your mirror.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Hit, smash, or use percussion devices on facial bones',
                        'DIY jaw / chin "expansion" devices',
                        'Topical steroids on the face for non-medical reasons',
                        'Research chemicals (MK-677, LGD, etc.) for "facial growth"',
                        'Mouth-tape if you have any sleep apnea suspicion',
                    ],
                },
                {
                    id: 'one-line',
                    number: '13.4',
                    title: 'The One-Sentence Rule',
                    subtitle: 'If a method causes injury, it is injury — not transformation.',
                    icon: 'leaf-outline',
                    eta: '1 min',
                    bullets: [
                        'Pain → injury',
                        'Swelling that doesn\'t fade → injury',
                        'Numbness → injury',
                        'Visible damage → injury',
                    ],
                },
            ],
        },

        /* ── Ch 14 ─────────────────────────────────────────────────── */
        {
            id: 'build-stack',
            number: 14,
            title: 'Build Your Stack',
            subtitle: 'Beginner / intermediate / advanced playbooks for the face.',
            icon: 'construct-outline',
            sections: [
                {
                    id: 'beginner',
                    number: '14.1',
                    title: 'Beginner Stack',
                    subtitle: 'Three habits, no gear, 4 weeks before adding anything.',
                    icon: 'medal-outline',
                    eta: '2 min',
                    bullets: [
                        'Posture: chin tucks 3×10 daily + screen at eye level',
                        'Tongue posture: practice all day, every day',
                        'Skin: gentle cleanser + moisturizer + SPF 30+',
                        'Sleep: 7–9 h consistent',
                    ],
                },
                {
                    id: 'intermediate',
                    number: '14.2',
                    title: 'Intermediate Stack',
                    subtitle: 'Add training, debloat, and basic fraudmaxxing.',
                    icon: 'medal',
                    eta: '2 min',
                    bullets: [
                        'Continue beginner stack',
                        'Resistance training 3×/week (with neck work 2×)',
                        'Daily debloat: cold splash + walk + 2 L water',
                        'Body comp: cut to 12–15% if higher',
                        'Beard / brow grooming',
                    ],
                },
                {
                    id: 'advanced',
                    number: '14.3',
                    title: 'Advanced Stack',
                    subtitle: 'Cycle harder protocols and refine the visual game.',
                    icon: 'trophy-outline',
                    eta: '2 min',
                    bullets: [
                        'Mastic gum 3×/week (15 min cap)',
                        'Photo every month — same lighting + angle',
                        'Pre-event 24h debloat protocol',
                        'Photographer-grade lighting setup at home for content',
                        'Bloodwork annually if supplementing chronically',
                    ],
                },
                {
                    id: 'tracking',
                    number: '14.4',
                    title: 'Tracking',
                    subtitle: 'Photos every 4 weeks. Same lighting. Same angle. No makeup.',
                    icon: 'image-outline',
                    eta: '1 min',
                    bullets: [
                        'Front + 3/4 + side profile every month',
                        'Bare skin, same window light, same time of day',
                        'Quarterly comparison reveals what daily mirror checks miss',
                        'Patience > panic',
                    ],
                },
            ],
        },
    ],
};
