/**
 * FITMAX course content. Body composition + training + nutrition + presentation.
 * Derived from rag_content/fitmax/*.md (the comprehensive coaching docs).
 * See ./courseContent.ts for the schema.
 */
import type { CourseModule } from './courseContent';

export const FITMAX_COURSE: CourseModule = {
    maxxId: 'fitmax',
    accent: '#10B981',
    accentSoft: 'rgba(16, 185, 129, 0.10)',
    accentMid: 'rgba(16, 185, 129, 0.20)',
    caption: '14 chapters · 60 lessons · built for newcomers',
    chapters: [
        /* ── Ch 1 ──────────────────────────────────────────────────── */
        {
            id: 'foundations',
            number: 1,
            title: 'Fitmaxxing Foundations',
            subtitle: 'A body that improves your face, frame, and presence — not just your scale.',
            icon: 'trophy-outline',
            sections: [
                {
                    id: 'what-it-is',
                    number: '1.1',
                    title: 'What Fitmaxxing Is',
                    subtitle: 'Visual return on investment. Some muscles change perception more than others.',
                    icon: 'eye-outline',
                    eta: '2 min',
                    bullets: [
                        'Goal: athletic, sharp, healthy, dominant — not bodybuilder unless you want to',
                        'Aesthetics = body fat × muscle distribution × posture × clothing × lighting',
                        'High-ROI muscles: side delts, lats, upper chest, neck, traps, arms',
                        'Train for a specific visual outcome — not random gym routines',
                    ],
                },
                {
                    id: 'aesthetic-hierarchy',
                    number: '1.2',
                    title: 'Aesthetic Hierarchy',
                    subtitle: 'Body fat first. Then proportions. Then size. In that order.',
                    icon: 'list-outline',
                    eta: '2 min',
                    bullets: [
                        '1. Body fat percentage — exposes everything else',
                        '2. Shoulder-to-waist ratio — width on top, tightness in middle',
                        '3. Muscle distribution — high-ROI muscles emphasized',
                        '4. Posture, clothing, presentation',
                    ],
                },
                {
                    id: 'fitmax-rule',
                    number: '1.3',
                    title: 'The Fitmaxxing Rule',
                    subtitle: 'Train for a specific visual outcome, not "general fitness."',
                    icon: 'compass-outline',
                    eta: '2 min',
                    bullets: [
                        'Does this exercise make my frame look better?',
                        'Does this habit make me leaner or fuller?',
                        'Does this improve my proportions?',
                        'Does this make me look better in clothes?',
                    ],
                },
                {
                    id: 'realistic-timelines',
                    number: '1.4',
                    title: 'Realistic Timelines',
                    subtitle: 'Cutting takes weeks. Building takes years. Plan accordingly.',
                    icon: 'hourglass-outline',
                    eta: '2 min',
                    bullets: [
                        'Visible cut: 6–12 weeks for 1% body fat drop',
                        'Visible muscle (newcomer): 8–12 weeks for first noticeable gains',
                        'Intermediate gains: 0.5–1 lb of muscle/month at best',
                        'Aesthetic transformation: 18–36 months',
                    ],
                },
            ],
        },

        /* ── Ch 2 ──────────────────────────────────────────────────── */
        {
            id: 'body-fat',
            number: 2,
            title: 'Body Fat & Leanness',
            subtitle: 'The master variable. Lean enough to show structure, full enough to function.',
            icon: 'analytics-outline',
            sections: [
                {
                    id: 'why-bodyfat',
                    number: '2.1',
                    title: 'Why Body Fat Drives Looks',
                    subtitle: 'Higher BF buries everything you built underneath.',
                    icon: 'eye-outline',
                    eta: '2 min',
                    bullets: [
                        'Blurs muscle definition',
                        'Hides the jawline',
                        'Widens the visual waist',
                        'Wrecks how clothes hang',
                    ],
                },
                {
                    id: 'ideal-range',
                    number: '2.2',
                    title: 'Ideal Aesthetic Range',
                    subtitle: '~12–15% for most men. Sustainable, sharp, energetic.',
                    icon: 'options-outline',
                    eta: '2 min',
                    bullets: [
                        'Abs lightly visible without flexing',
                        'Face sharp, jawline visible',
                        'Energy intact, training stays heavy',
                        'Going below 10% is optional, hard to maintain',
                    ],
                },
                {
                    id: 'cut-math',
                    number: '2.3',
                    title: 'The Cutting Math',
                    subtitle: 'Calorie deficit + protein retention + lifting heavy.',
                    icon: 'calculator-outline',
                    eta: '3 min',
                    bullets: [
                        'Maintenance: bodyweight (lb) × 14–16',
                        'Cut deficit: 300–500 below maintenance',
                        '0.5–1% bodyweight loss per week — faster = muscle loss',
                        'Protein 0.8–1 g/lb. Steps 8–10k/day. Lift heavy.',
                    ],
                },
                {
                    id: 'avoid-flat',
                    number: '2.4',
                    title: 'Cut Without Looking Worse',
                    subtitle: 'Bad cuts make you smaller, weaker, and tired-looking.',
                    icon: 'shield-outline',
                    eta: '2 min',
                    bullets: [
                        'Keep carbs in (40–50% of total calories minimum)',
                        'Keep sodium consistent — don\'t yo-yo',
                        'Sleep 7–9 hours',
                        'If pumps disappear and workouts collapse, eat 100–200 cal more',
                    ],
                },
                {
                    id: 'maintenance-phases',
                    number: '2.5',
                    title: 'Maintenance Phases',
                    subtitle: 'Diet breaks every 6–8 weeks protect hormones and sanity.',
                    icon: 'pause-circle-outline',
                    eta: '2 min',
                    bullets: [
                        '2–4 weeks at maintenance after every 6–8 cutting weeks',
                        'Mood, sleep, performance all rebound',
                        'Next cut works better',
                        'Long uninterrupted cuts → diminishing returns',
                    ],
                },
            ],
        },

        /* ── Ch 3 ──────────────────────────────────────────────────── */
        {
            id: 'proportions',
            number: 3,
            title: 'Aesthetic Proportions',
            subtitle: 'Contrast > size. The V-taper is built deliberately.',
            icon: 'triangle-outline',
            sections: [
                {
                    id: 'v-taper',
                    number: '3.1',
                    title: 'The V-Taper Equation',
                    subtitle: 'Wide on top, tight in the middle. Both ends amplify each other.',
                    icon: 'expand-outline',
                    eta: '2 min',
                    bullets: [
                        'Side delts → shoulder width',
                        'Lats → upper-back width',
                        'Lean enough to expose the waist',
                        'Avoid heavy oblique training (boxy waist)',
                    ],
                },
                {
                    id: 'side-delts-priority',
                    number: '3.2',
                    title: 'Side Delts Are Priority',
                    subtitle: 'Highest-ROI muscle for aesthetics. Train them often.',
                    icon: 'barbell-outline',
                    eta: '3 min',
                    bullets: [
                        'Cable lateral raises — main movement',
                        'Lean-away laterals — strict form, full ROM',
                        'Behind-the-back cable laterals — different angle',
                        'Cue: lead with elbows, traps relaxed, control the negative',
                    ],
                },
                {
                    id: 'lats',
                    number: '3.3',
                    title: 'Lats',
                    subtitle: 'Width from front and back. The other half of the V.',
                    icon: 'expand-outline',
                    eta: '2 min',
                    bullets: [
                        'Neutral-grip pulldowns, pull-ups, prayer pulldowns',
                        'Drive elbows DOWN and back, not just hands toward you',
                        '8–15 rep range, controlled tempo',
                        '12–18 sets per week if lats lag',
                    ],
                },
                {
                    id: 'upper-chest',
                    number: '3.4',
                    title: 'Upper Chest',
                    subtitle: 'Fills the gap between shoulders and chest. Without it the torso looks empty.',
                    icon: 'shirt-outline',
                    eta: '2 min',
                    bullets: [
                        'Low-incline DB press, incline Smith, machine incline',
                        '15–30° incline — anything steeper turns it into front delt',
                        'Pause in the stretch position',
                        '8–12 reps, 3–4 sets, 2× per week',
                    ],
                },
                {
                    id: 'neck-traps-arms',
                    number: '3.5',
                    title: 'Neck, Traps, Arms, Forearms',
                    subtitle: 'The smaller-but-essential muscles for proportionality.',
                    icon: 'fitness-outline',
                    eta: '2 min',
                    bullets: [
                        'Neck: 2× per week, light, slow, controlled',
                        'Traps: shrugs 3×12 — proportionate to head size',
                        'Long head triceps: overhead extensions for arm size',
                        'Forearms: hammer curls, dead hangs, farmer carries',
                    ],
                },
            ],
        },

        /* ── Ch 4 ──────────────────────────────────────────────────── */
        {
            id: 'splits',
            number: 4,
            title: 'Workout Splits',
            subtitle: 'The split matters less than volume, recovery, and consistency.',
            icon: 'calendar-outline',
            sections: [
                {
                    id: 'core-principle',
                    number: '4.1',
                    title: 'The Core Principle',
                    subtitle: '~10–12 hard sets per muscle per week, spread across days.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Volume × intensity × recovery > "perfect" split',
                        '6 sets Monday + 6 sets Thursday > 12 sets Monday',
                        '2× per week per muscle is the sweet spot',
                        'Quality reps near failure > junk volume',
                    ],
                },
                {
                    id: 'full-body',
                    number: '4.2',
                    title: '3-Day Full Body',
                    subtitle: 'Best for beginners and busy people. High frequency, easy recovery.',
                    icon: 'grid-outline',
                    eta: '2 min',
                    bullets: [
                        'Mon / Wed / Fri',
                        '2–3 compounds + 2–3 accessories per session',
                        'Easy to learn form, easy to recover from',
                        'Optimal for first 6–12 months of training',
                    ],
                },
                {
                    id: 'upper-lower',
                    number: '4.3',
                    title: '4-Day Upper / Lower',
                    subtitle: 'Best for intermediate lifters who want structure.',
                    icon: 'apps-outline',
                    eta: '2 min',
                    bullets: [
                        'Mon Upper / Tue Lower / Thu Upper / Fri Lower',
                        'Each muscle hit twice per week',
                        'Great recovery, easy progression',
                        'Balanced upper and lower development',
                    ],
                },
                {
                    id: 'ppl',
                    number: '4.4',
                    title: 'Push / Pull / Legs',
                    subtitle: 'High-volume option for people who like training often.',
                    icon: 'repeat-outline',
                    eta: '2 min',
                    bullets: [
                        'Push: chest, shoulders, triceps',
                        'Pull: back, rear delts, biceps',
                        'Legs: quads, hamstrings, calves, glutes',
                        '6 days (PPL/PPL/Rest) or 5 days with rotating rest day',
                    ],
                },
                {
                    id: 'volume',
                    number: '4.5',
                    title: 'Volume Guidelines',
                    subtitle: 'How much is enough. How much is too much.',
                    icon: 'speedometer-outline',
                    eta: '2 min',
                    bullets: [
                        'Maintenance: 6–10 sets/muscle/week',
                        'Growth: 10–16 sets/muscle/week',
                        'Specialization (short blocks): 16–22 sets/muscle/week',
                        'Above 22 = diminishing returns + risk of overtraining',
                    ],
                },
            ],
        },

        /* ── Ch 5 ──────────────────────────────────────────────────── */
        {
            id: 'muscle-growth',
            number: 5,
            title: 'Muscle Growth Framework',
            subtitle: 'Tension + overload + proximity to failure + recovery. That\'s it.',
            icon: 'flame-outline',
            sections: [
                {
                    id: 'mechanical-tension',
                    number: '5.1',
                    title: 'Mechanical Tension',
                    subtitle: 'The primary driver of hypertrophy. Especially in the stretched position.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Don\'t bounce reps — control the bottom',
                        'Get a real stretch in the lengthened position',
                        'Squeeze the contraction, don\'t just move weight',
                        'Soreness is feedback — not the goal',
                    ],
                },
                {
                    id: 'progressive-overload',
                    number: '5.2',
                    title: 'Progressive Overload',
                    subtitle: 'Increase demands over time. Multiple ways to do it.',
                    icon: 'trending-up-outline',
                    eta: '3 min',
                    bullets: [
                        'Add weight at the same reps',
                        'Add reps at the same weight',
                        'Add a set',
                        'Tighten form so the target muscle does more of the work',
                    ],
                },
                {
                    id: 'proximity-failure',
                    number: '5.3',
                    title: 'Proximity to Failure',
                    subtitle: '0–3 reps in reserve. The last 5 reps drive most of the growth.',
                    icon: 'flash-outline',
                    eta: '3 min',
                    bullets: [
                        'Working sets: stop with 0–3 reps in the tank',
                        'Sets stopped 5+ reps short = mostly junk volume',
                        'Form should hold all the way to the last rep',
                        'If form breaks 4 reps from failure, drop the weight',
                    ],
                },
                {
                    id: 'frequency',
                    number: '5.4',
                    title: 'Frequency',
                    subtitle: '1–3 times per muscle per week, depending on level + recovery.',
                    icon: 'calendar-outline',
                    eta: '2 min',
                    bullets: [
                        '1×/week: only for advanced lifters with very high per-session volume',
                        '2×/week: sweet spot for most',
                        '3×/week: useful for lagging muscles or skill-heavy lifts',
                    ],
                },
                {
                    id: 'when-not-growing',
                    number: '5.5',
                    title: 'When You\'re Not Growing',
                    subtitle: 'Audit in this exact order before changing your program.',
                    icon: 'help-circle-outline',
                    eta: '3 min',
                    bullets: [
                        '1. Are you actually progressing weight or reps over 4 weeks?',
                        '2. Are you eating enough? (Bodyweight should creep up if growing)',
                        '3. Are you sleeping enough? (Track for 2 weeks honestly)',
                        '4. Are you training to ~2 RIR or less?',
                    ],
                },
            ],
        },

        /* ── Ch 6 ──────────────────────────────────────────────────── */
        {
            id: 'exercise-library',
            number: 6,
            title: 'Exercise Library',
            subtitle: 'High-ROI movements per body part. Pick 1–2, run for 6–8 weeks.',
            icon: 'library-outline',
            sections: [
                {
                    id: 'chest-exercises',
                    number: '6.1',
                    title: 'Chest',
                    subtitle: 'Upper, mid, lower — different incline angles target each.',
                    icon: 'fitness-outline',
                    eta: '3 min',
                    bullets: [
                        'Upper: low-incline DB press, incline Smith, machine incline',
                        'Mid: pec deck, machine press, cable fly',
                        'Lower: dips, cable cross-under fly',
                        'Cue: control the stretch, no bouncing',
                    ],
                },
                {
                    id: 'back-exercises',
                    number: '6.2',
                    title: 'Back',
                    subtitle: 'Width (lats) + thickness (rows) + rear delts (3D look).',
                    icon: 'expand-outline',
                    eta: '3 min',
                    bullets: [
                        'Width: neutral-grip pulldowns, pull-ups, lat prayer',
                        'Thickness: chest-supported rows, machine rows, cable rows',
                        'Rear delts: reverse pec deck, cable rear delt fly',
                        'Posterior chain: back extensions, RDLs',
                    ],
                },
                {
                    id: 'shoulder-exercises',
                    number: '6.3',
                    title: 'Shoulders',
                    subtitle: 'Side delts >>> front delts for aesthetics.',
                    icon: 'barbell-outline',
                    eta: '2 min',
                    bullets: [
                        'Side: cable laterals, lean-away, behind-the-back cable',
                        'Front: shoulder press (don\'t over-prioritize)',
                        'Rear: reverse pec deck, cable rear delt fly',
                        'Cue: lead with elbows, traps stay relaxed',
                    ],
                },
                {
                    id: 'arm-exercises',
                    number: '6.4',
                    title: 'Arms',
                    subtitle: 'Long head triceps + biceps. Both visible in everything.',
                    icon: 'hand-right-outline',
                    eta: '2 min',
                    bullets: [
                        'Biceps: preacher curl, Bayesian curl, incline DB curl, cable curl',
                        'Triceps: cable pushdown, OVERHEAD extension (long head!), skullcrushers, dips',
                        'Long head triceps drive arm size from the side angle',
                        '2–3 exercises per week for each, 8–15 reps',
                    ],
                },
                {
                    id: 'leg-exercises',
                    number: '6.5',
                    title: 'Legs',
                    subtitle: 'Quads, hams, calves, glutes — athletic balance, not just size.',
                    icon: 'walk-outline',
                    eta: '2 min',
                    bullets: [
                        'Quads: hack squat, leg press, pendulum, leg extension',
                        'Hams: lying / seated leg curl, RDL',
                        'Calves: standing + seated, heavy and slow',
                        'Glutes: hip thrust, Bulgarian split squat',
                    ],
                },
                {
                    id: 'neck-core',
                    number: '6.6',
                    title: 'Neck, Core',
                    subtitle: 'Often skipped. Both matter for the visual frame.',
                    icon: 'man-outline',
                    eta: '2 min',
                    bullets: [
                        'Neck curls + extensions, light + slow',
                        '2–3× per week for neck',
                        'Core: cable crunch, hanging leg raise, planks',
                        'Skip heavy oblique work — boxy waist',
                    ],
                },
            ],
        },

        /* ── Ch 7 ──────────────────────────────────────────────────── */
        {
            id: 'nutrition',
            number: 7,
            title: 'Nutrition',
            subtitle: 'Diet should make you look better AND train better.',
            icon: 'restaurant-outline',
            sections: [
                {
                    id: 'protein',
                    number: '7.1',
                    title: 'Protein',
                    subtitle: 'The non-negotiable macro. 0.7–1 g per lb bodyweight.',
                    icon: 'nutrition-outline',
                    eta: '2 min',
                    bullets: [
                        'General: ~0.7 g/lb',
                        'Aggressive cut: ~1 g/lb',
                        'Distribute across 3–5 meals, ≥30g each',
                        'Sources: chicken, beef, Greek yogurt, eggs, whey, fish',
                    ],
                },
                {
                    id: 'carbs',
                    number: '7.2',
                    title: 'Carbs',
                    subtitle: 'Not the enemy. They fuel training and keep muscles full.',
                    icon: 'pizza-outline',
                    eta: '2 min',
                    bullets: [
                        'Drive glycogen, pumps, strength, recovery',
                        'Best timed pre/post-workout',
                        'Sources: rice, potatoes, oats, fruit, cream of rice',
                        'Low-carb diets make you flat and weak — usually wrong for hypertrophy',
                    ],
                },
                {
                    id: 'fats',
                    number: '7.3',
                    title: 'Fats',
                    subtitle: 'Support hormones and satiety. Easy to over-eat — measure.',
                    icon: 'water-outline',
                    eta: '2 min',
                    bullets: [
                        'Sources: eggs, olive oil, avocado, fatty fish, nuts',
                        'Don\'t eliminate — just control',
                        'Calorie-dense: a "spoonful" of nut butter is 200+ cal',
                        '20–30% of total calories is the safe range',
                    ],
                },
                {
                    id: 'macro-setup',
                    number: '7.4',
                    title: 'Macro Setup',
                    subtitle: 'High carb, medium protein, medium-low fat for most builds.',
                    icon: 'pie-chart-outline',
                    eta: '2 min',
                    bullets: [
                        'Maintenance / lean bulk: high carb, mid protein, low fat',
                        'Cut: high protein, moderate carb, low fat',
                        'Aggressive cut: very high protein (1g/lb), keep some carbs',
                    ],
                },
                {
                    id: 'hydration',
                    number: '7.5',
                    title: 'Hydration',
                    subtitle: '2–3 L water/day baseline. Electrolytes if you sweat heavy.',
                    icon: 'water-outline',
                    eta: '1 min',
                    bullets: [
                        '2–3 L baseline',
                        '+500 mL per hour intense training',
                        'Electrolytes (sodium + potassium) if sweating > 1 hour',
                        'Coffee and beer count partially toward fluid (not all)',
                    ],
                },
            ],
        },

        /* ── Ch 8 ──────────────────────────────────────────────────── */
        {
            id: 'dieting-hacks',
            number: 8,
            title: 'Dieting Hacks',
            subtitle: 'Tools to lose fat without losing your sanity or your pump.',
            icon: 'sparkles-outline',
            sections: [
                {
                    id: 'high-volume-foods',
                    number: '8.1',
                    title: 'High-Volume Foods',
                    subtitle: 'Real volume of food without spiking calories.',
                    icon: 'restaurant-outline',
                    eta: '2 min',
                    bullets: [
                        'Rice cakes, diet soda, Greek yogurt, egg whites',
                        'Low-carb tortillas, lean ground beef',
                        'Protein ice cream (Halo Top, Nick\'s)',
                        'Vegetables and fruit (filling, fiber, micros)',
                    ],
                },
                {
                    id: 'hunger-control',
                    number: '8.2',
                    title: 'Hunger Control',
                    subtitle: 'Most "willpower" failures are just inadequate hunger management.',
                    icon: 'shield-outline',
                    eta: '2 min',
                    bullets: [
                        'Morning caffeine suppresses appetite',
                        'High-fiber foods at every meal',
                        'Sugar-free gum between meals',
                        'Last meal close to bedtime',
                    ],
                },
                {
                    id: 'weekly-budget',
                    number: '8.3',
                    title: 'Weekly Calorie Budgeting',
                    subtitle: 'Bank calories for social meals. Weekly average drives results.',
                    icon: 'calendar-outline',
                    eta: '2 min',
                    bullets: [
                        'Mon–Fri lower, Saturday higher (social meal)',
                        'Sunday return to baseline',
                        'Weekly average is what matters',
                        'Beats white-knuckling perfect daily adherence',
                    ],
                },
                {
                    id: 'cut-without-flat',
                    number: '8.4',
                    title: 'Cutting Without Looking Flat',
                    subtitle: 'A bad cut wrecks your appearance. Avoid the obvious traps.',
                    icon: 'trending-up-outline',
                    eta: '2 min',
                    bullets: [
                        'Keep carbs in (40–50% of calories minimum)',
                        'Sodium consistent — don\'t yo-yo',
                        '<1% bodyweight loss per week',
                        'Keep lifting heavy at the same rep ranges',
                    ],
                },
                {
                    id: 'diet-breaks',
                    number: '8.5',
                    title: 'Diet Breaks',
                    subtitle: 'Every 6–8 weeks, eat at maintenance for 1–2 weeks.',
                    icon: 'pause-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Hormones rebound (leptin, T3, testosterone)',
                        'Mood, sleep, strength all improve',
                        'Next cut works better',
                        'Sustainability beats perfection',
                    ],
                },
            ],
        },

        /* ── Ch 9 ──────────────────────────────────────────────────── */
        {
            id: 'lean-bulking',
            number: 9,
            title: 'Lean Bulking',
            subtitle: 'Small surplus = real muscle without face fat or wrecked V-taper.',
            icon: 'arrow-up-circle-outline',
            sections: [
                {
                    id: 'when-to-bulk',
                    number: '9.1',
                    title: 'When To Bulk',
                    subtitle: 'Underweight, lacking visible muscle, or strength stalled.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Underweight for your height',
                        'Lack visible muscle even when lean',
                        'Strength stalled 6+ weeks',
                        'Look skinny in fitted clothes',
                    ],
                },
                {
                    id: 'lean-bulk-math',
                    number: '9.2',
                    title: 'The Math',
                    subtitle: 'Maintenance + 200–300 calories. 0.25–0.5 lb/week.',
                    icon: 'calculator-outline',
                    eta: '2 min',
                    bullets: [
                        'Surplus: maintenance + 200–300 calories',
                        'Expected gain: 0.25–0.5 lb/week',
                        '>1 lb/week = mostly fat — drop surplus by 100',
                        'Track 7-day average bodyweight, ignore daily noise',
                    ],
                },
                {
                    id: 'bulking-foods',
                    number: '9.3',
                    title: 'Bulking Foods',
                    subtitle: 'Calorie-dense and digestible.',
                    icon: 'restaurant-outline',
                    eta: '2 min',
                    bullets: [
                        'Rice with sauce, fatty fish, whole eggs, less-lean meats',
                        'Pasta with olive oil + protein',
                        'Smoothies (oats + banana + PB + whey + milk)',
                        'Olive oil drizzled on meals — easy calorie add',
                    ],
                },
                {
                    id: 'appetite-hacks',
                    number: '9.4',
                    title: 'Appetite Hacks',
                    subtitle: 'For those who struggle to eat enough.',
                    icon: 'flask-outline',
                    eta: '2 min',
                    bullets: [
                        'Liquid calories (smoothies, milk)',
                        'Lower-volume calorie-dense foods',
                        'Walk after meals to speed digestion',
                        'Don\'t overload fiber — fills you up too fast',
                    ],
                },
                {
                    id: 'dirty-bulk-trap',
                    number: '9.5',
                    title: 'The Dirty Bulk Trap',
                    subtitle: 'Eating "anything that fits" wrecks face, waist, confidence.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Face fat (the part nobody warns you about)',
                        'Worse skin (insulin spikes, processed food)',
                        'V-taper destroyed',
                        'Brutal multi-month cut afterward',
                    ],
                },
            ],
        },

        /* ── Ch 10 ─────────────────────────────────────────────────── */
        {
            id: 'supplements',
            number: 10,
            title: 'Supplements',
            subtitle: 'Support tools, not magic. A few are real; most are marketing.',
            icon: 'flask-outline',
            sections: [
                {
                    id: 'tier-1',
                    number: '10.1',
                    title: 'Tier 1 — Real Evidence',
                    subtitle: 'Creatine, whey, caffeine, electrolytes.',
                    icon: 'medal-outline',
                    eta: '3 min',
                    bullets: [
                        'Creatine monohydrate 3–5g/day, every day',
                        'Whey or plant protein — convenient food',
                        'Caffeine 100–300mg pre-workout',
                        'Electrolytes when sweating heavy',
                    ],
                },
                {
                    id: 'tier-2',
                    number: '10.2',
                    title: 'Tier 2 — Situational',
                    subtitle: 'Vitamin D, magnesium, omega-3 — useful with deficiencies.',
                    icon: 'medal',
                    eta: '2 min',
                    bullets: [
                        'Vitamin D3 1000–2000 IU if sun is low',
                        'Magnesium glycinate 200–400mg at night',
                        'Omega-3s 1–2g combined EPA+DHA',
                        'Test before chronic supplementation',
                    ],
                },
                {
                    id: 'pre-workout',
                    number: '10.3',
                    title: 'Pre-Workout Stack',
                    subtitle: 'DIY beats most branded pre-workouts.',
                    icon: 'rocket-outline',
                    eta: '2 min',
                    bullets: [
                        'Caffeine 200mg + L-theanine 100–200mg (smooths jitters)',
                        'Citrulline malate 6–8g (pump and endurance)',
                        'Carbs 30–50g pre-session',
                        'Skip "natural test boosters" and proprietary blends',
                    ],
                },
                {
                    id: 'cope-supplements',
                    number: '10.4',
                    title: 'Cope Supplements',
                    subtitle: 'Things that promise steroid-like results without being steroids.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        '"Natural test boosters" — don\'t move test in healthy lifters',
                        'Turkesterone — meta-analyses unimpressed',
                        'Random "anabolic blends" — under-dosed proprietary blends',
                        'Shilajit from sketchy sources — heavy metal contamination risk',
                    ],
                },
            ],
        },

        /* ── Ch 11 ─────────────────────────────────────────────────── */
        {
            id: 'recovery',
            number: 11,
            title: 'Recovery & Lifestyle',
            subtitle: 'Muscle is built outside the gym. Recovery debt = no progress.',
            icon: 'bed-outline',
            sections: [
                {
                    id: 'why-recovery',
                    number: '11.1',
                    title: 'Why Recovery Matters',
                    subtitle: 'The gym creates the stimulus. Recovery does the building.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Bad recovery → weak workouts, no pumps, constant soreness',
                        'Three+ symptoms → audit recovery, not training',
                        'Sleep + protein + carbs > supplements',
                        'Rest 1–2 full days per week, no exceptions',
                    ],
                },
                {
                    id: 'sleep-master',
                    number: '11.2',
                    title: 'Sleep — Master Variable',
                    subtitle: 'GH peaks during deep sleep. Cortisol drops overnight.',
                    icon: 'moon-outline',
                    eta: '2 min',
                    bullets: [
                        '7–9 hours, consistent ±30 min',
                        'Cool room (65–68°F)',
                        'No alcohol within 4 h of bed',
                        'Last meal 2–3 h before bed',
                    ],
                },
                {
                    id: 'overtraining',
                    number: '11.3',
                    title: 'Overtraining Signs',
                    subtitle: 'When the answer is less, not more.',
                    icon: 'warning-outline',
                    eta: '2 min',
                    bullets: [
                        'Strength dropping 2+ sessions in a row',
                        'No motivation, no pump',
                        'Constant joint aches',
                        'Getting sick more than usual',
                    ],
                },
                {
                    id: 'hygiene',
                    number: '11.4',
                    title: 'Hygiene',
                    subtitle: 'A built body with bad hygiene loses impact.',
                    icon: 'shirt-outline',
                    eta: '2 min',
                    bullets: [
                        'Shower after every workout',
                        'Clean clothes — gym shirts get bacterial fast',
                        'Don\'t drown in cologne — light spritz at the chest only',
                        'Air out gym shoes, don\'t leave wet clothes in your bag',
                    ],
                },
            ],
        },

        /* ── Ch 12 ─────────────────────────────────────────────────── */
        {
            id: 'posture-clothing',
            number: 12,
            title: 'Posture & Clothing',
            subtitle: 'Posture changes perceived physique instantly. Clothes amplify what you built.',
            icon: 'man-outline',
            sections: [
                {
                    id: 'posture-matters',
                    number: '12.1',
                    title: 'Why Posture Matters',
                    subtitle: 'Same body, dramatically different perception.',
                    icon: 'eye-outline',
                    eta: '2 min',
                    bullets: [
                        'Good posture: taller, broader, leaner, more athletic',
                        'Common problems: forward head, rounded shoulders, anterior pelvic tilt',
                        'Train: rear delts, mid traps, glutes, neck extensors',
                        'Should look natural, not military-stiff',
                    ],
                },
                {
                    id: 'shirt-fit',
                    number: '12.2',
                    title: 'Shirt Fit Rules',
                    subtitle: 'A great shirt amplifies your frame. A bad one hides it.',
                    icon: 'shirt-outline',
                    eta: '2 min',
                    bullets: [
                        'Sleeve hugs the arm slightly',
                        'Shoulder seam sits on your actual shoulder',
                        'Chest has structure',
                        'Waist not baggy, fabric not too thin',
                    ],
                },
                {
                    id: 'jackets',
                    number: '12.3',
                    title: 'Jackets',
                    subtitle: 'Add structure on top + hide waist softness.',
                    icon: 'shirt-outline',
                    eta: '2 min',
                    bullets: [
                        'Bomber, denim, leather, overshirt, structured cropped jacket',
                        'Layering: fitted shirt + structured jacket = max width',
                        'Skip oversized streetwear if you\'re trying to look athletic',
                    ],
                },
                {
                    id: 'pants-shoes',
                    number: '12.4',
                    title: 'Pants & Shoes',
                    subtitle: 'Lower body fits matter as much as the top.',
                    icon: 'walk-outline',
                    eta: '2 min',
                    bullets: [
                        'Athletic taper, straight fit, room in thighs',
                        'Avoid super skinny jeans (look weak on developed legs)',
                        'Avoid extremely baggy (shapeless)',
                        'Slight platform / chunky sneakers / clean white sneakers',
                    ],
                },
                {
                    id: 'color',
                    number: '12.5',
                    title: 'Color Tricks',
                    subtitle: 'Dark slims, light lifts, monochrome elongates.',
                    icon: 'color-palette-outline',
                    eta: '1 min',
                    bullets: [
                        'Dark colors slim the waist',
                        'Light upper body makes chest/shoulders pop',
                        'Monochrome reads taller and more put-together',
                    ],
                },
            ],
        },

        /* ── Ch 13 ─────────────────────────────────────────────────── */
        {
            id: 'photo-camera',
            number: 13,
            title: 'Photo & Camera',
            subtitle: 'Pre-photo pump, the right angle, the right lighting.',
            icon: 'camera-outline',
            sections: [
                {
                    id: 'pre-photo',
                    number: '13.1',
                    title: 'Pre-Photo Pump',
                    subtitle: 'Get blood in the muscles right before the photo.',
                    icon: 'flash-outline',
                    eta: '2 min',
                    bullets: [
                        'Push-ups 2–3 sets of 10–15',
                        'Lateral raises 2 sets of 12–15',
                        'Curls 2 sets',
                        'Light carbs 90 min before — fuller, not bloated',
                    ],
                },
                {
                    id: 'angles',
                    number: '13.2',
                    title: 'Best Angles',
                    subtitle: 'Mirror at chest height. 3/4 rotation. Lats flared.',
                    icon: 'aperture-outline',
                    eta: '2 min',
                    bullets: [
                        'Camera at chest height or slightly lower',
                        '3/4 torso rotation — never directly square',
                        'Arms slightly out from body, never pinned',
                        'Limb closer to camera looks bigger',
                    ],
                },
                {
                    id: 'lighting',
                    number: '13.3',
                    title: 'Lighting',
                    subtitle: 'Side or slight overhead. Never flat front-flash.',
                    icon: 'sunny-outline',
                    eta: '2 min',
                    bullets: [
                        'Slight overhead (gym lighting is perfect)',
                        'Side lighting at 45° sculpts shoulders, arms, chest',
                        'Natural window light from an angle',
                        'Avoid: flat front light, harsh bathroom light, direct flash',
                    ],
                },
                {
                    id: 'phone-limits',
                    number: '13.4',
                    title: 'Phone Camera Limits',
                    subtitle: 'Front cameras are wide-angle and distort. Use the back.',
                    icon: 'phone-portrait-outline',
                    eta: '2 min',
                    bullets: [
                        'Use back camera, not front',
                        'Have someone else take it',
                        'Stand 6–10 feet from the camera, not arm\'s length',
                        '50mm-equivalent or longer = most natural proportions',
                    ],
                },
            ],
        },

        /* ── Ch 14 ─────────────────────────────────────────────────── */
        {
            id: 'mistakes',
            number: 14,
            title: 'Common Mistakes',
            subtitle: 'The patterns that hold most lifters back.',
            icon: 'alert-circle-outline',
            sections: [
                {
                    id: 'training-mistakes',
                    number: '14.1',
                    title: 'Training Mistakes',
                    subtitle: 'Changing exercises, junk volume, ego lifting.',
                    icon: 'remove-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Changing exercises every 2–3 weeks — can\'t track progress',
                        'Junk volume — sets only count if hard and recoverable',
                        'Ego lifting — heavy weight + bad form = no tension on target',
                        'Skipping side delts and lats',
                    ],
                },
                {
                    id: 'diet-mistakes',
                    number: '14.2',
                    title: 'Diet Mistakes',
                    subtitle: 'Dirty bulking, crash cutting, avoiding carbs.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Dirty bulking — fast gain = mostly fat',
                        'Crash cutting — lose fullness, strength, energy',
                        'Avoiding carbs — kills performance and pumps',
                        'Liquid calories you forget (cream + sugar coffee, beer)',
                    ],
                },
                {
                    id: 'aesthetic-mistakes',
                    number: '14.3',
                    title: 'Aesthetic Mistakes',
                    subtitle: 'The patterns that build wrong-shaped bodies.',
                    icon: 'body-outline',
                    eta: '2 min',
                    bullets: [
                        'Only training chest and arms (top-heavy frame)',
                        'Letting waist get too big during a bulk',
                        'Never training neck, calves, or rear delts',
                        'Excessive direct ab/oblique work (boxy waist)',
                    ],
                },
                {
                    id: 'meta-mistake',
                    number: '14.4',
                    title: 'The Meta-Mistake',
                    subtitle: 'Inconsistency. The unsexy truth that beats everything else.',
                    icon: 'time-outline',
                    eta: '2 min',
                    bullets: [
                        'Mediocre program ran perfectly for 2 years > perfect program for 6 weeks',
                        'Pick a plan, run it 12 weeks minimum',
                        'Track. Adjust. Repeat.',
                        '85% adherence over years > 100% adherence for months',
                    ],
                },
            ],
        },
    ],
};
