// AUTO-SYNCED from maxapp:data/courses/hairmax.ts by scripts/sync-from-maxapp.mjs — do not edit here.
// Edit the source in the maxapp repo, then re-run the sync.
/**
 * HAIRMAX course content. Hair loss + hair quality. See ./courseContent.ts
 * for the schema.
 */
import type { CourseModule } from './courseContent';

export const HAIRMAX_COURSE: CourseModule = {
    maxxId: 'hairmax',
    accent: '#3B82F6',
    accentSoft: 'rgba(59, 130, 246, 0.10)',
    accentMid: 'rgba(59, 130, 246, 0.20)',
    caption: '13 chapters · 56 lessons · built for newcomers',
    chapters: [
        /* ── Ch 1 ──────────────────────────────────────────────────── */
        {
            id: 'foundations',
            number: 1,
            title: 'Hair Foundations',
            subtitle: 'Start here. The hair lifecycle and what you can actually change.',
            icon: 'leaf-outline',
            sections: [
                {
                    id: 'hair-anatomy',
                    number: '1.1',
                    title: 'Hair Anatomy',
                    subtitle: 'Follicle, shaft, sebaceous gland, root — what each part does.',
                    icon: 'layers-outline',
                    eta: '3 min',
                    bullets: [
                        'Follicle: the bulb that grows the strand',
                        'Shaft: the visible part — already dead protein',
                        'Sebaceous gland: oil supply, also DHT-sensitive',
                        'Dermal papilla: vascular signal — what you protect',
                    ],
                },
                {
                    id: 'growth-cycle',
                    number: '1.2',
                    title: 'The Growth Cycle',
                    subtitle: 'Anagen, catagen, telogen — most loss is shortened anagen.',
                    icon: 'refresh-outline',
                    eta: '3 min',
                    bullets: [
                        'Anagen: 2–7 year growth phase',
                        'Catagen: 2–3 week transition (regression)',
                        'Telogen: 3 month rest then shed',
                        'AGA shortens anagen and miniaturizes the follicle each cycle',
                    ],
                },
                {
                    id: 'why-hair-falls',
                    number: '1.3',
                    title: 'Why Hair Falls',
                    subtitle: 'Genetics + DHT for most men. Other causes can mimic.',
                    icon: 'warning-outline',
                    eta: '3 min',
                    bullets: [
                        'AGA (male/female pattern): genetics + DHT sensitivity',
                        'Telogen effluvium: stress, illness, deficiency — usually reversible',
                        'Alopecia areata: autoimmune patches',
                        'Traction: tight ponytails, helmets, hats',
                    ],
                },
                {
                    id: 'whats-controllable',
                    number: '1.4',
                    title: 'What You Can Change',
                    subtitle: 'Genetics set the ceiling. Habits set the floor.',
                    icon: 'options-outline',
                    eta: '2 min',
                    bullets: [
                        'DHT sensitivity (finasteride suppresses)',
                        'Follicle nourishment (minoxidil increases)',
                        'Mechanical insult (handling, washing, tension)',
                        'Scalp inflammation (ketoconazole, microbiome)',
                    ],
                },
                {
                    id: 'realistic-timelines',
                    number: '1.5',
                    title: 'Realistic Timelines',
                    subtitle: 'Hair is slow. Most progress is invisible until month 4.',
                    icon: 'hourglass-outline',
                    eta: '2 min',
                    bullets: [
                        'Shed phase: weeks 4–10 (terminal hairs cycling out, vellus emerging)',
                        'Stabilization: 3–6 months on min/fin',
                        'Visible regrowth: 6–12 months',
                        'Full effect: 18–24 months consistent stack',
                    ],
                },
            ],
        },

        /* ── Ch 2 ──────────────────────────────────────────────────── */
        {
            id: 'reading-hair',
            number: 2,
            title: 'Reading Your Hair Loss',
            subtitle: 'Diagnose before treating. Pattern matters.',
            icon: 'eye-outline',
            sections: [
                {
                    id: 'norwood-scale',
                    number: '2.1',
                    title: 'The Norwood Scale',
                    subtitle: 'Standard 1–7 chart for male pattern progression.',
                    icon: 'analytics-outline',
                    eta: '3 min',
                    bullets: [
                        'NW1: no recession — baseline',
                        'NW2: minor temple recession (mature hairline ≠ AGA)',
                        'NW3: clear M-shape, often the start of treatment',
                        'NW4–6: progressive crown thinning + temple deepening',
                        'NW7: only horseshoe ring — surgical territory',
                    ],
                },
                {
                    id: 'aga-vs-other',
                    number: '2.2',
                    title: 'AGA vs Other Causes',
                    subtitle: 'Pattern + timeline distinguishes most cases.',
                    icon: 'git-branch-outline',
                    eta: '3 min',
                    bullets: [
                        'AGA: gradual, patterned (temples + crown), starts post-puberty',
                        'TE: diffuse all-over shed 2–4 months after a trigger',
                        'AA: round patches with smooth bare skin',
                        'Traction: thinning along styling tension lines',
                    ],
                },
                {
                    id: 'mirror-test',
                    number: '2.3',
                    title: 'The Mirror Test',
                    subtitle: 'How to baseline yourself with photos.',
                    icon: 'camera-outline',
                    eta: '2 min',
                    bullets: [
                        'Same lighting, same angle, monthly',
                        'Front, top-down, both temples, crown',
                        'Bare scalp visible (no styling)',
                        'Compare months 0, 3, 6, 12',
                    ],
                },
                {
                    id: 'shed-vs-loss',
                    number: '2.4',
                    title: 'Shed vs True Loss',
                    subtitle: 'Counting hairs in your hand is the wrong metric.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        '50–100 hairs/day shedding is normal',
                        'Density and ground texture matter more than count',
                        'Look for scalp visibility under bright light from above',
                        'Vellus → terminal regrowth is the real sign minoxidil works',
                    ],
                },
                {
                    id: 'when-derm',
                    number: '2.5',
                    title: 'When To See A Dermatologist',
                    subtitle: 'Some patterns need a real diagnosis.',
                    icon: 'medical-outline',
                    eta: '2 min',
                    bullets: [
                        'Sudden diffuse loss (rule out TE, thyroid, deficiency)',
                        'Bare patches or scarring',
                        'Itching, burning, or visible scalp redness',
                        'Considering finasteride (Rx required, get a baseline first)',
                    ],
                },
            ],
        },

        /* ── Ch 3 ──────────────────────────────────────────────────── */
        {
            id: 'minoxidil',
            number: 3,
            title: 'Minoxidil',
            subtitle: 'The OTC anchor of every modern hair-loss stack.',
            icon: 'water-outline',
            sections: [
                {
                    id: 'minoxidil-mechanism',
                    number: '3.1',
                    title: 'How Minoxidil Works',
                    subtitle: 'Vasodilator + ATP energy boost — extends anagen, thickens shaft.',
                    icon: 'flash-outline',
                    eta: '3 min',
                    bullets: [
                        'Opens scalp microvasculature',
                        'Pushes follicles back into anagen growth phase',
                        'Vellus → terminal hair conversion over 4–8 months',
                        'Stops working if you stop applying — lifelong commitment',
                    ],
                },
                {
                    id: 'minoxidil-dose',
                    number: '3.2',
                    title: 'Dose & Format',
                    subtitle: '5% solution or foam. Once or twice daily.',
                    icon: 'beaker-outline',
                    eta: '3 min',
                    bullets: [
                        '5% liquid (Kirkland, generic) — cheapest',
                        '5% foam (Rogaine) — less greasy, no propylene glycol',
                        '1 mL twice daily, or 2 mL once daily — same total',
                        '2% women\'s formula deprecated; 5% is the standard for both',
                    ],
                },
                {
                    id: 'minoxidil-application',
                    number: '3.3',
                    title: 'Application Technique',
                    subtitle: 'On dry scalp, not hair. Massage in. Wait 4 hours.',
                    icon: 'hand-left-outline',
                    eta: '2 min',
                    bullets: [
                        'Apply to dry scalp at the thinning area',
                        'Massage briefly to spread; do not rinse',
                        'Wait 4 hours before swimming, sweating, or styling',
                        'Wash hands after; minoxidil affects body hair if rubbed elsewhere',
                    ],
                },
                {
                    id: 'minoxidil-shed',
                    number: '3.4',
                    title: 'The Initial Shed',
                    subtitle: 'Weeks 2–8 of shedding is the drug working — do not panic.',
                    icon: 'trending-down-outline',
                    eta: '3 min',
                    bullets: [
                        'Old telogen hairs get pushed out as new anagen begins',
                        'Lasts 2–8 weeks then resolves',
                        'Stopping during shed restarts the loss cycle',
                        'Signal of response, not failure — push through it',
                    ],
                },
                {
                    id: 'minoxidil-side-effects',
                    number: '3.5',
                    title: 'Side Effects',
                    subtitle: 'Usually mild. Skin irritation is the main quit reason.',
                    icon: 'alert-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Scalp dryness/itching from propylene glycol — switch to foam',
                        'Unwanted facial/body hair (rare, from runoff)',
                        'Heart palpitations: stop, see a doctor',
                        'Edema (face puffiness): rare with topical, possible with oral',
                    ],
                },
            ],
        },

        /* ── Ch 4 ──────────────────────────────────────────────────── */
        {
            id: 'finasteride',
            number: 4,
            title: 'Finasteride',
            subtitle: 'The DHT blocker. Most effective, most controversial.',
            icon: 'shield-checkmark-outline',
            sections: [
                {
                    id: 'fin-mechanism',
                    number: '4.1',
                    title: 'How Finasteride Works',
                    subtitle: 'Blocks 5α-reductase — drops scalp DHT ~70%.',
                    icon: 'flash-outline',
                    eta: '3 min',
                    bullets: [
                        'DHT is the androgen that miniaturizes follicles',
                        'Finasteride inhibits its conversion from testosterone',
                        'Stops the AGA process at the source',
                        'Takes 3–6 months to show visible benefit',
                    ],
                },
                {
                    id: 'fin-dose',
                    number: '4.2',
                    title: 'Dose & Cadence',
                    subtitle: '1 mg daily oral is the standard. Topical is a newer option.',
                    icon: 'beaker-outline',
                    eta: '2 min',
                    bullets: [
                        'Oral: 1 mg/day (Propecia generic)',
                        'Some users do 1.25 mg every other day — equally effective in studies',
                        'Topical 0.25%: lower systemic exposure, similar local effect',
                        'Take at consistent time; food intake does not matter',
                    ],
                },
                {
                    id: 'fin-side-effects',
                    number: '4.3',
                    title: 'Side Effects — The Honest Picture',
                    subtitle: 'Real but uncommon. Discuss with a doctor before starting.',
                    icon: 'alert-circle-outline',
                    eta: '4 min',
                    bullets: [
                        'Sexual: ~2–4% report libido or function changes',
                        'Mood: small subset report low mood / brain fog',
                        'Most resolve on cessation; some persist (PFS — rare)',
                        'Get baseline labs + sexual function self-assessment first',
                    ],
                    body:
                        'Most large studies show side-effect rates similar to placebo, but a real minority ' +
                        'experience persistent issues. Topical and oral both carry the risk; topical is lower. ' +
                        'Have an honest conversation with a clinician — informed consent matters here.',
                },
                {
                    id: 'fin-bloodwork',
                    number: '4.4',
                    title: 'Bloodwork & Monitoring',
                    subtitle: 'Baseline + periodic checks let you catch issues early.',
                    icon: 'analytics-outline',
                    eta: '2 min',
                    bullets: [
                        'Pre-start: testosterone, free T, PSA (if 40+)',
                        'PSA halves on fin — multiply lab values by 2 for interpretation',
                        '6 months in: re-check labs, document any symptom changes',
                        'Stop if persistent unwanted side effects — don\'t white-knuckle',
                    ],
                },
                {
                    id: 'fin-vs-dut',
                    number: '4.5',
                    title: 'Finasteride vs Dutasteride',
                    subtitle: 'Dut blocks more isoforms but with stronger systemic profile.',
                    icon: 'swap-horizontal-outline',
                    eta: '2 min',
                    bullets: [
                        'Fin blocks type 2 → ~70% scalp DHT reduction',
                        'Dut blocks types 1 & 2 → ~90% scalp DHT reduction',
                        'Dut: longer half-life, stronger sustained effect',
                        'Off-label for AGA — discuss with a derm before switching',
                    ],
                },
            ],
        },

        /* ── Ch 5 ──────────────────────────────────────────────────── */
        {
            id: 'dermarolling',
            number: 5,
            title: 'Microneedling / Dermarolling',
            subtitle: 'Mild scalp injury triggers growth signals. Boosts minoxidil.',
            icon: 'medkit-outline',
            sections: [
                {
                    id: 'dr-protocol',
                    number: '5.1',
                    title: 'The Protocol',
                    subtitle: '0.5 mm roller, once per week, on dry scalp.',
                    icon: 'options-outline',
                    eta: '3 min',
                    bullets: [
                        '0.5 mm needle length — sweet spot for hair (longer = scarring risk)',
                        '1×/week — every 7 days, never daily',
                        'Roll horizontal, vertical, both diagonals — 10–15 passes each',
                        'Skip minoxidil for 24 h after to avoid systemic absorption spike',
                    ],
                },
                {
                    id: 'dr-with-min',
                    number: '5.2',
                    title: 'Pairing With Minoxidil',
                    subtitle: 'Studies show 5x better growth combined vs minoxidil alone.',
                    icon: 'git-merge-outline',
                    eta: '2 min',
                    bullets: [
                        'Roll on dry scalp evening 1',
                        'Wait 24 hours before next minoxidil dose',
                        'Resume normal application thereafter',
                        'Channels close in 24 h — beyond that no special prep needed',
                    ],
                },
                {
                    id: 'dr-safety',
                    number: '5.3',
                    title: 'Safety Rules',
                    subtitle: 'A cheap mistake here means scarring.',
                    icon: 'shield-outline',
                    eta: '3 min',
                    bullets: [
                        'Sterilize roller before/after every use (70% iso)',
                        'Replace roller every 8–12 sessions (~3 months)',
                        'Stop if scalp bleeds heavily or stays red >24 h',
                        'Never use on active scalp infection or cysts',
                    ],
                },
                {
                    id: 'dr-vs-stamp',
                    number: '5.4',
                    title: 'Roller vs Stamp',
                    subtitle: 'Stamps puncture deeper but cover less; rollers are easier home use.',
                    icon: 'swap-horizontal-outline',
                    eta: '2 min',
                    bullets: [
                        'Roller: easier, covers larger area, slight angle on shaft',
                        'Stamp: precise depth, less drag-trauma, slower',
                        'For home use: roller is forgiving and proven',
                        'For very localized thinning: stamp can be more efficient',
                    ],
                },
            ],
        },

        /* ── Ch 6 ──────────────────────────────────────────────────── */
        {
            id: 'scalp-health',
            number: 6,
            title: 'Scalp Health',
            subtitle: 'A healthy scalp grows healthy hair. Inflammation kills follicles.',
            icon: 'leaf-outline',
            sections: [
                {
                    id: 'sebum-balance',
                    number: '6.1',
                    title: 'Sebum & Wash Frequency',
                    subtitle: 'Wash often enough that sebum doesn\'t suffocate follicles.',
                    icon: 'water-outline',
                    eta: '2 min',
                    bullets: [
                        'Oily scalp: shampoo every other day or daily',
                        'Dry scalp: 2–3× per week, gentle sulfate-free',
                        'Co-wash days: condition only, no shampoo',
                        'Rinse cool — hot water strips and irritates',
                    ],
                },
                {
                    id: 'ketoconazole',
                    number: '6.2',
                    title: 'Ketoconazole',
                    subtitle: 'Anti-fungal shampoo with mild anti-DHT effects on scalp.',
                    icon: 'flask-outline',
                    eta: '3 min',
                    bullets: [
                        'Nizoral 1% (OTC) or 2% (Rx)',
                        '2× per week, leave on 5 minutes before rinsing',
                        'Reduces inflammation; weakly inhibits scalp DHT',
                        'Adjunct only — not a replacement for min/fin',
                    ],
                },
                {
                    id: 'microbiome',
                    number: '6.3',
                    title: 'Scalp Microbiome',
                    subtitle: 'Like gut bacteria — balance matters more than sterility.',
                    icon: 'flower-outline',
                    eta: '2 min',
                    bullets: [
                        'Healthy biome resists Malassezia overgrowth (dandruff cause)',
                        'Avoid daily harsh sulfates that wipe protective species',
                        'Rotate gentle and medicated shampoos',
                        'Probiotic shampoos: emerging, not yet evidence-strong',
                    ],
                },
                {
                    id: 'inflammation-signs',
                    number: '6.4',
                    title: 'Inflammation Signs',
                    subtitle: 'Treat the cause; chronic inflammation thins hair.',
                    icon: 'thermometer-outline',
                    eta: '2 min',
                    bullets: [
                        'Persistent itch, redness, flaking',
                        'Burning sensation after shampoo',
                        'Sensitivity at the parting',
                        'See a dermatologist if symptoms persist 4+ weeks',
                    ],
                },
            ],
        },

        /* ── Ch 7 ──────────────────────────────────────────────────── */
        {
            id: 'topical-stack',
            number: 7,
            title: 'Topical Stack Layering',
            subtitle: 'How to combine min, fin, derm, ketoconazole without conflicts.',
            icon: 'layers-outline',
            sections: [
                {
                    id: 'daily-stack',
                    number: '7.1',
                    title: 'A Standard Daily Stack',
                    subtitle: 'Morning + evening with minimal friction.',
                    icon: 'calendar-outline',
                    eta: '3 min',
                    bullets: [
                        'AM: minoxidil 1 mL, dry scalp (or skip if 1×/day)',
                        'AM oral: finasteride 1 mg with breakfast',
                        'PM: minoxidil 1 mL on dry scalp',
                        'Wash days: ketoconazole 2× per week',
                    ],
                },
                {
                    id: 'weekly-stack',
                    number: '7.2',
                    title: 'Adding Microneedling',
                    subtitle: 'One night per week, swap minoxidil out for 24 hours.',
                    icon: 'time-outline',
                    eta: '2 min',
                    bullets: [
                        'Sunday PM: dermaroll on dry scalp, no minoxidil after',
                        'Monday: skip both AM and PM minoxidil',
                        'Tuesday: resume normal cadence',
                        'Repeat weekly',
                    ],
                },
                {
                    id: 'order-of-application',
                    number: '7.3',
                    title: 'Order Of Application',
                    subtitle: 'Topicals on dry scalp before any styling product.',
                    icon: 'swap-vertical-outline',
                    eta: '2 min',
                    bullets: [
                        'Always: clean dry scalp first',
                        'Topical actives before any oils, gels, or creams',
                        'Wait 30 min before styling product layer',
                        'Sleep on a cotton pillowcase only after 4+ hours dry',
                    ],
                },
            ],
        },

        /* ── Ch 8 ──────────────────────────────────────────────────── */
        {
            id: 'lifestyle',
            number: 8,
            title: 'Diet & Lifestyle',
            subtitle: 'Sleep and stress aren\'t supplements — they\'re the foundation.',
            icon: 'sunny-outline',
            sections: [
                {
                    id: 'sleep-hair',
                    number: '8.1',
                    title: 'Sleep',
                    subtitle: 'Consistent sleep windows protect the hair growth cycle.',
                    icon: 'moon-outline',
                    eta: '2 min',
                    bullets: [
                        '7–9 hours, consistent ±30 min',
                        'Scalp circulation peaks during deep sleep',
                        'Chronic sleep loss accelerates AGA progression',
                        'Sleep apnea correlates with worse outcomes — get tested if snoring',
                    ],
                },
                {
                    id: 'stress',
                    number: '8.2',
                    title: 'Stress & Cortisol',
                    subtitle: 'Chronic stress shifts more follicles into telogen (shedding).',
                    icon: 'pulse-outline',
                    eta: '3 min',
                    bullets: [
                        'Acute stress shed shows up 2–4 months later',
                        'Cortisol blunts dermal papilla signaling',
                        'Walking, breathwork, social contact help measurably',
                        'Consider therapy or pharmacology for ongoing high stress',
                    ],
                },
                {
                    id: 'diet-deficiencies',
                    number: '8.3',
                    title: 'Diet & Deficiencies',
                    subtitle: 'Iron, ferritin, vitamin D, B12, zinc — the usual suspects.',
                    icon: 'restaurant-outline',
                    eta: '3 min',
                    bullets: [
                        'Ferritin <70 ng/mL correlates with hair loss in many studies',
                        'Vitamin D <30 ng/mL: supplement to mid-50s',
                        'B12 <500 pg/mL: especially relevant for vegans',
                        'Get bloodwork if unexplained shedding — supplementing blind is wasted',
                    ],
                },
                {
                    id: 'smoking-alcohol',
                    number: '8.4',
                    title: 'Smoking & Alcohol',
                    subtitle: 'Both reduce scalp microcirculation. Both worsen AGA.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Smoking: vasoconstriction, oxidative stress, accelerated AGA',
                        'Heavy alcohol: dehydration, sleep disruption, deficiency',
                        'Cutting either visibly improves shedding within 8 weeks',
                        'Vaping is not a free pass — same vasoconstriction',
                    ],
                },
                {
                    id: 'training-hair',
                    number: '8.5',
                    title: 'Training & Hormones',
                    subtitle: 'Resistance training is fine. Anabolics are a different conversation.',
                    icon: 'barbell-outline',
                    eta: '2 min',
                    bullets: [
                        'Normal training has no effect on AGA progression',
                        'Anabolic steroids accelerate shedding sharply',
                        'High-dose creatine: small DHT bump, mixed evidence on hair',
                        'Sweat then shower — don\'t let salt sit on the scalp for hours',
                    ],
                },
            ],
        },

        /* ── Ch 9 ──────────────────────────────────────────────────── */
        {
            id: 'supplements',
            number: 9,
            title: 'Adjuncts & Supplements',
            subtitle: 'Most "hair vitamins" are placebos. A few have real evidence.',
            icon: 'flask-outline',
            sections: [
                {
                    id: 'biotin-myth',
                    number: '9.1',
                    title: 'The Biotin Myth',
                    subtitle: 'Useless unless you\'re actually deficient. Most people aren\'t.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Biotin deficiency is rare (raw eggs daily, certain meds)',
                        'Supplementing without deficiency does nothing for hair',
                        'Can interfere with some lab tests (thyroid panels)',
                        'Save your money — the marketing > the science',
                    ],
                },
                {
                    id: 'vitamin-d-iron',
                    number: '9.2',
                    title: 'Vitamin D + Iron',
                    subtitle: 'The two with the strongest correlation data for hair loss.',
                    icon: 'sunny-outline',
                    eta: '3 min',
                    bullets: [
                        'Vitamin D 1000–2000 IU/day if low',
                        'Iron + vitamin C if ferritin is below 70',
                        'Test before supplementing iron (excess is harmful)',
                        'Magnesium glycinate at night — supports sleep, indirectly hair',
                    ],
                },
                {
                    id: 'saw-palmetto',
                    number: '9.3',
                    title: 'Saw Palmetto',
                    subtitle: 'Mild DHT inhibition. A weaker, OTC alternative to finasteride.',
                    icon: 'leaf-outline',
                    eta: '2 min',
                    bullets: [
                        '320 mg standardized extract daily',
                        'Real but small effect on DHT',
                        'Useful for those refusing finasteride',
                        'Not a replacement if AGA is progressing fast',
                    ],
                },
                {
                    id: 'collagen-keratin',
                    number: '9.4',
                    title: 'Collagen, Keratin, MSM',
                    subtitle: 'Marketed for hair quality. Mixed evidence at best.',
                    icon: 'help-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Collagen peptides: useful for skin, weak for hair',
                        'Keratin pills: digested as protein, no follicle delivery',
                        'MSM (sulfur): tiny benefit if dietary protein low',
                        'Skip these in favor of bloodwork-driven supplementation',
                    ],
                },
            ],
        },

        /* ── Ch 10 ─────────────────────────────────────────────────── */
        {
            id: 'restoration',
            number: 10,
            title: 'Restoration & Cosmetic',
            subtitle: 'When topicals stop being enough — transplants, fibers, SMP.',
            icon: 'construct-outline',
            sections: [
                {
                    id: 'transplant-overview',
                    number: '10.1',
                    title: 'Hair Transplant Basics',
                    subtitle: 'FUE vs FUT. Donor area is finite — choose surgeon carefully.',
                    icon: 'medkit-outline',
                    eta: '4 min',
                    bullets: [
                        'FUE: extracts individual follicles — minimal scarring',
                        'FUT: strip-harvest, more grafts in one session, linear scar',
                        'Donor area = back of head, finite supply',
                        'Stay on min/fin afterward — protects native hair',
                    ],
                },
                {
                    id: 'transplant-readiness',
                    number: '10.2',
                    title: 'Are You Ready?',
                    subtitle: 'Stabilize loss first. Bad timing = chasing your hairline forever.',
                    icon: 'time-outline',
                    eta: '3 min',
                    bullets: [
                        'Be on min/fin for 12+ months first',
                        'Loss should be stable for 6 months pre-surgery',
                        'NW3+ generally — too early and you\'ll need touch-ups for life',
                        'Realistic expectations: density restored, not full teenage hair',
                    ],
                },
                {
                    id: 'smp',
                    number: '10.3',
                    title: 'Scalp Micropigmentation',
                    subtitle: 'Tattooed dot pattern that mimics shaved-head density.',
                    icon: 'color-palette-outline',
                    eta: '2 min',
                    bullets: [
                        'Best for buzz-cut style end goal',
                        '2–3 sessions, lasts 3–7 years before touch-up',
                        'Looks artificial if attempted to mimic long hair',
                        'Find an artist with a strong portfolio of healed work',
                    ],
                },
                {
                    id: 'fibers-concealer',
                    number: '10.4',
                    title: 'Fibers & Concealer',
                    subtitle: 'Same-day cosmetic fix for thinning areas.',
                    icon: 'sparkles-outline',
                    eta: '2 min',
                    bullets: [
                        'Toppik / Caboki: keratin fibers electrostatically bind to existing hair',
                        'Apply to dry styled hair, set with hairspray',
                        'Survives wind/light rain, washes out',
                        'Color-matched scalp concealer for thin parting lines',
                    ],
                },
            ],
        },

        /* ── Ch 11 ─────────────────────────────────────────────────── */
        {
            id: 'styling',
            number: 11,
            title: 'Styling & Grooming',
            subtitle: 'The right cut buys you years of perceived density.',
            icon: 'cut-outline',
            sections: [
                {
                    id: 'cut-for-thinning',
                    number: '11.1',
                    title: 'Cuts For Thinning',
                    subtitle: 'Shorter on the sides, balanced top, no comb-overs.',
                    icon: 'options-outline',
                    eta: '3 min',
                    bullets: [
                        'Buzz cut (#2–4): fully owns it, looks deliberate',
                        'Crew cut: short top, fades, masculine and modern',
                        'Texture crop: uneven layers add visual density',
                        'Avoid: comb-overs, slicked-back styles, long fringes that part',
                    ],
                },
                {
                    id: 'product-volume',
                    number: '11.2',
                    title: 'Volumizing Products',
                    subtitle: 'Matte texture and lift make hair look thicker than it is.',
                    icon: 'flask-outline',
                    eta: '2 min',
                    bullets: [
                        'Matte clay > shiny pomade for thinning hair',
                        'Sea salt spray for volume on damp hair',
                        'Hair powder at the roots for instant lift',
                        'Avoid heavy gels that clump strands and reveal scalp',
                    ],
                },
                {
                    id: 'color',
                    number: '11.3',
                    title: 'Color',
                    subtitle: 'Lightening hair vs scalp contrast hides thin spots.',
                    icon: 'color-palette-outline',
                    eta: '2 min',
                    bullets: [
                        'Lighter hair color reduces scalp/hair contrast → less visible thinning',
                        'Avoid very dark dyes unless density is solid',
                        'Henna: temporary, low-damage option',
                        'For greys: blend with low-tone color, don\'t over-cover',
                    ],
                },
                {
                    id: 'hat-helmet',
                    number: '11.4',
                    title: 'Hats, Helmets, Headphones',
                    subtitle: 'Tight headwear for hours = traction at the hairline.',
                    icon: 'hardware-chip-outline',
                    eta: '2 min',
                    bullets: [
                        'Loose-fitting hats are fine; tight beanies all day are not',
                        'Wash hats / headbands / helmet pads weekly',
                        'Headphone bands at the same spot daily can thin a strip',
                        'Bike helmet: rotate position, dry sweat-free between uses',
                    ],
                },
            ],
        },

        /* ── Ch 12 ─────────────────────────────────────────────────── */
        {
            id: 'mistakes',
            number: 12,
            title: 'Common Mistakes',
            subtitle: 'The patterns that quietly burn months of progress.',
            icon: 'alert-circle-outline',
            sections: [
                {
                    id: 'quitting-shed',
                    number: '12.1',
                    title: 'Quitting During The Shed',
                    subtitle: 'The most expensive mistake. The shed IS the drug working.',
                    icon: 'remove-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Weeks 2–8 shed = telogen hairs cycling out',
                        'Quitting = restart at zero',
                        'Photo every month, look at month 4–6',
                        'Trust the protocol, not the daily mirror',
                    ],
                },
                {
                    id: 'skipping-fin',
                    number: '12.2',
                    title: 'Minoxidil Without Finasteride',
                    subtitle: 'You can grow new hair but the underlying loss continues.',
                    icon: 'trending-down-outline',
                    eta: '2 min',
                    bullets: [
                        'Minoxidil grows hair but doesn\'t address DHT',
                        'AGA progression continues underneath',
                        'After 2–3 years you may be losing as fast as you grow',
                        'Add fin (or saw palmetto if refusing fin) to address the cause',
                    ],
                },
                {
                    id: 'inconsistency',
                    number: '12.3',
                    title: 'Inconsistent Application',
                    subtitle: 'Skipping 2 days a week = significant efficacy loss.',
                    icon: 'calendar-outline',
                    eta: '2 min',
                    bullets: [
                        'Minoxidil: half-life is ~22 hours — daily is non-negotiable',
                        'Set phone alarms for AM and PM application',
                        'Travel kit: foam is easier than liquid in luggage',
                        '85% adherence is the threshold for visible results',
                    ],
                },
                {
                    id: 'too-many-products',
                    number: '12.4',
                    title: 'Stacking Snake Oil',
                    subtitle: 'New "miracle" oils and serums every 6 months — pick proven, stop changing.',
                    icon: 'layers-outline',
                    eta: '2 min',
                    bullets: [
                        'Pick the proven stack: minoxidil + finasteride + dermaroll + nizoral',
                        'Add nothing new for 12 months minimum',
                        'Rosemary oil: small evidence, not a min/fin replacement',
                        'Hair growth pills with 30 ingredients: marketing, not medicine',
                    ],
                },
            ],
        },

        /* ── Ch 13 ─────────────────────────────────────────────────── */
        {
            id: 'build-stack',
            number: 13,
            title: 'Build Your Personal Stack',
            subtitle: 'Beginner / intermediate / advanced playbooks. Pick your tier.',
            icon: 'construct-outline',
            sections: [
                {
                    id: 'beginner-stack',
                    number: '13.1',
                    title: 'Beginner Stack',
                    subtitle: 'Under $30/month. Two interventions. Run for 6 months.',
                    icon: 'medal-outline',
                    eta: '2 min',
                    bullets: [
                        'Kirkland 5% minoxidil 1 mL twice daily (~$10/mo)',
                        'Nizoral 1% shampoo 2× per week (~$10/mo, lasts 3+ months)',
                        'Skip everything else for 6 months',
                        'Photo monthly; reassess at month 6',
                    ],
                },
                {
                    id: 'intermediate-stack',
                    number: '13.2',
                    title: 'Intermediate Stack',
                    subtitle: 'Add finasteride and dermarolling once you\'re committed.',
                    icon: 'medal',
                    eta: '3 min',
                    bullets: [
                        'Continue minoxidil + Nizoral baseline',
                        'Finasteride 1 mg/day oral OR 0.25% topical',
                        'Dermaroll 0.5 mm 1× per week',
                        'Bloodwork at baseline + 6 months',
                    ],
                },
                {
                    id: 'advanced-stack',
                    number: '13.3',
                    title: 'Advanced / Aggressive Stack',
                    subtitle: 'For fast progressors or NW4+ wanting maximum effect.',
                    icon: 'trophy-outline',
                    eta: '3 min',
                    bullets: [
                        'Oral minoxidil 1.25–2.5 mg/day (Rx, monitored)',
                        'Dutasteride 0.5 mg 2–3×/week (off-label, with derm)',
                        'Microneedling stamp 1 mm, biweekly',
                        'Consider PRP injections quarterly',
                    ],
                },
                {
                    id: 'tracking',
                    number: '13.4',
                    title: 'Tracking Results',
                    subtitle: 'Photos + photos + photos. The mirror lies daily.',
                    icon: 'image-outline',
                    eta: '2 min',
                    bullets: [
                        'Same lighting, same angle, same hair length',
                        'Front, top-down, both temples, crown — 5 angles',
                        'Monthly cadence; review every 3 months',
                        'Six-month comparisons reveal what daily mirror checks miss',
                    ],
                },
            ],
        },
    ],
};
