/**
 * HEIGHTMAX course content. Posture, decompression, perceived height,
 * vertical-read styling. See ./courseContent.ts for the schema.
 */
import type { CourseModule } from './courseContent';

export const HEIGHTMAX_COURSE: CourseModule = {
    maxxId: 'heightmax',
    accent: '#6366F1',
    accentSoft: 'rgba(99, 102, 241, 0.10)',
    accentMid: 'rgba(99, 102, 241, 0.20)',
    caption: '12 chapters · 50 lessons · built for newcomers',
    chapters: [
        /* ── Ch 1 ──────────────────────────────────────────────────── */
        {
            id: 'foundations',
            number: 1,
            title: 'Height Foundations',
            subtitle: 'What\'s genetic, what\'s perception, what\'s actually under your control.',
            icon: 'leaf-outline',
            sections: [
                {
                    id: 'real-vs-perceived',
                    number: '1.1',
                    title: 'Real vs Perceived Height',
                    subtitle: 'Real: bone-length. Perceived: posture, frame, styling, photo.',
                    icon: 'eye-outline',
                    eta: '2 min',
                    bullets: [
                        'Real height = bone length (genetic, fixed in adults)',
                        'Perceived height = posture + frame + clothing + lighting',
                        '1–2 inches of perceived height is realistic via posture alone',
                        'Decompression adds 0.5–1.5 cm of measured height (transient)',
                    ],
                },
                {
                    id: 'genetic-window',
                    number: '1.2',
                    title: 'The Genetic Window',
                    subtitle: 'Most growth ends when growth plates close.',
                    icon: 'hourglass-outline',
                    eta: '2 min',
                    bullets: [
                        'Plates close: men ~16–21, women ~14–19',
                        'Open plates: nutrition + sleep + activity matter most',
                        'Closed plates: only surgery genuinely lengthens bone',
                        'X-ray confirms whether yours are open',
                    ],
                },
                {
                    id: 'daily-variation',
                    number: '1.3',
                    title: 'Daily Height Variation',
                    subtitle: 'You\'re ~1 cm taller in the morning. Use it.',
                    icon: 'trending-down-outline',
                    eta: '1 min',
                    bullets: [
                        'Spinal disc compression loses 0.5–2 cm through the day',
                        'Morning measurements always taller',
                        'Decompression drills restore some compression',
                        'Sleep (lying flat) is the main "decompressor"',
                    ],
                },
                {
                    id: 'whats-controllable',
                    number: '1.4',
                    title: 'What You Can Change',
                    subtitle: 'Posture, mobility, fascia, footwear, framing.',
                    icon: 'options-outline',
                    eta: '2 min',
                    bullets: [
                        'Posture: forward-head + slumped shoulders cost 1–2 inches',
                        'Mobility: tight hip flexors and pecs steal vertical line',
                        'Footwear: shoes can add 1–4 inches honestly',
                        'Clothing: vertical lines, monochrome, fit',
                        'Photo angles: camera height changes perceived height',
                    ],
                },
                {
                    id: 'realistic-expectations',
                    number: '1.5',
                    title: 'Realistic Expectations',
                    subtitle: 'A clear ceiling. Aim for "looking taller", not actual growth in adults.',
                    icon: 'shield-checkmark-outline',
                    eta: '2 min',
                    bullets: [
                        'Adults: 1–2 inches of perceived height via posture is realistic',
                        '+1–4 inches via footwear depending on style',
                        'Surgery (limb lengthening): real but invasive, expensive, long recovery',
                        'Most "grew 4 inches" anecdotes are posture + decompression + measurement timing',
                    ],
                },
            ],
        },

        /* ── Ch 2 ──────────────────────────────────────────────────── */
        {
            id: 'posture-mechanics',
            number: 2,
            title: 'Posture Mechanics',
            subtitle: 'The three patterns that steal inches from your stand.',
            icon: 'man-outline',
            sections: [
                {
                    id: 'forward-head',
                    number: '2.1',
                    title: 'Forward Head Posture',
                    subtitle: 'Each inch of forward head adds ~10 lb of effective head weight.',
                    icon: 'walk-outline',
                    eta: '2 min',
                    bullets: [
                        'Caused by chronic screen time at low height',
                        'Cervical lordosis flattens, head juts forward',
                        'Shortens visible neck length',
                        'Fix: chin tucks + raise screen to eye level',
                    ],
                },
                {
                    id: 'kyphosis',
                    number: '2.2',
                    title: 'Thoracic Kyphosis (Hunched Back)',
                    subtitle: 'Rounded upper back tips the head forward and shortens the torso.',
                    icon: 'walk-outline',
                    eta: '3 min',
                    bullets: [
                        'Common in desk workers and lifters with weak rear delts',
                        'Costs visible chest height + makes shoulders look narrower',
                        'Fix: thoracic mobility + rear delt + lat work',
                        'Foam roller across upper back, 2 min daily',
                    ],
                },
                {
                    id: 'apt',
                    number: '2.3',
                    title: 'Anterior Pelvic Tilt',
                    subtitle: 'Tight hip flexors + weak glutes tip the pelvis forward, costing posture height.',
                    icon: 'body-outline',
                    eta: '3 min',
                    bullets: [
                        'Hip flexors short from sitting, glutes weak from inactivity',
                        'Lower-back arch increases, belly pushes forward',
                        'Fix: hip flexor stretches + glute bridges + planks',
                        '5 min daily routine, results in 4–8 weeks',
                    ],
                },
                {
                    id: 'audit',
                    number: '2.4',
                    title: 'Self-Audit',
                    subtitle: 'Stand against a wall, ankles to head touching. Where do you fail?',
                    icon: 'analytics-outline',
                    eta: '2 min',
                    bullets: [
                        'Heels, butt, upper back, head all touching the wall = ideal',
                        'Head doesn\'t reach: forward head posture',
                        'Lower back arches strongly: anterior pelvic tilt',
                        'Upper back rounds: thoracic kyphosis',
                    ],
                },
                {
                    id: 'daily-cues',
                    number: '2.5',
                    title: 'Daily Cues',
                    subtitle: 'Practice posture all day, not just at the gym.',
                    icon: 'time-outline',
                    eta: '2 min',
                    bullets: [
                        'Crown of head reaching for the ceiling',
                        'Ribcage stacked over pelvis (no rib flare)',
                        'Shoulders relaxed and slightly back',
                        'Chin neutral (not jutting forward)',
                    ],
                },
            ],
        },

        /* ── Ch 3 ──────────────────────────────────────────────────── */
        {
            id: 'decompression',
            number: 3,
            title: 'Spinal Decompression',
            subtitle: 'Restore the disc height your day stole. Real, but measurable in cm not inches.',
            icon: 'arrow-up-outline',
            sections: [
                {
                    id: 'why-decompression',
                    number: '3.1',
                    title: 'Why Decompression Works',
                    subtitle: 'Discs absorb fluid when off-loaded. Off-load them deliberately.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Discs lose hydration under daily compression',
                        'Off-loading restores some height transiently',
                        'Sleep does most of the work (lying flat 7–9 h)',
                        'Daily decompression drills add a measurable bonus',
                    ],
                },
                {
                    id: 'dead-hangs',
                    number: '3.2',
                    title: 'Dead Hangs',
                    subtitle: 'Pull-up bar, full body relaxed, gravity does the work.',
                    icon: 'fitness-outline',
                    eta: '2 min',
                    bullets: [
                        '30 seconds × 3 sets, twice daily',
                        'Full body relaxed — let gravity stretch the spine',
                        'Don\'t engage the lats — passive only',
                        'Add weight via vest after 4 weeks if comfortable',
                    ],
                },
                {
                    id: 'inversion',
                    number: '3.3',
                    title: 'Inversion Tables',
                    subtitle: 'Hang upside down to off-load the spine. Great if no contraindications.',
                    icon: 'arrow-up-outline',
                    eta: '2 min',
                    bullets: [
                        'Start at 30° for 1–2 min, build up',
                        '10–15 min at 60–90° max',
                        'Skip if: high blood pressure, glaucoma, heart issues',
                        'Best in evening — counters day\'s compression',
                    ],
                },
                {
                    id: 'cobra-extension',
                    number: '3.4',
                    title: 'Cobra & Spinal Extension',
                    subtitle: 'Open chest, extend spine, decompress thoracic.',
                    icon: 'walk-outline',
                    eta: '2 min',
                    bullets: [
                        'Cobra pose: 30s × 3, breathing deeply',
                        'Foam roller thoracic extension: 1–2 min',
                        'Open-book stretches for thoracic rotation',
                        'Daily, especially after long sitting',
                    ],
                },
                {
                    id: 'stack-protocol',
                    number: '3.5',
                    title: 'Daily Decompression Stack',
                    subtitle: '10 minutes that restore visible height by evening.',
                    icon: 'calendar-outline',
                    eta: '2 min',
                    bullets: [
                        'AM: dead hangs 30s × 3',
                        'Mid-day: cobra + thoracic extension',
                        'PM: dead hangs again or inversion 5 min',
                        'Sleep: side or back, no stomach (compresses spine)',
                    ],
                },
            ],
        },

        /* ── Ch 4 ──────────────────────────────────────────────────── */
        {
            id: 'mobility',
            number: 4,
            title: 'Mobility & Stretching',
            subtitle: 'Tight tissue compresses you. Loose tissue lets you stand tall.',
            icon: 'body-outline',
            sections: [
                {
                    id: 'hip-flexor',
                    number: '4.1',
                    title: 'Hip Flexor Stretches',
                    subtitle: 'Tight hip flexors are the main APT culprit. Stretch daily.',
                    icon: 'walk-outline',
                    eta: '3 min',
                    bullets: [
                        'Couch stretch: 60s each side, 2× daily',
                        'Kneeling hip flexor stretch: 60s × 2 each',
                        'Pigeon pose for outer hip rotators',
                        'Most desk workers need 4–8 weeks to see real change',
                    ],
                },
                {
                    id: 'pec-stretch',
                    number: '4.2',
                    title: 'Pec Stretches',
                    subtitle: 'Tight pecs round the shoulders and tip the head forward.',
                    icon: 'expand-outline',
                    eta: '2 min',
                    bullets: [
                        'Doorway pec stretch: 30s × 3 each side',
                        'Foam roller across upper back, arms overhead',
                        'Especially needed if you bench heavy without rear delt work',
                        'Daily — 30 seconds is plenty',
                    ],
                },
                {
                    id: 'hamstring',
                    number: '4.3',
                    title: 'Hamstring Mobility',
                    subtitle: 'Tight hams pull the pelvis into posterior tilt — also bad.',
                    icon: 'walk-outline',
                    eta: '2 min',
                    bullets: [
                        'Hamstring stretch: 30s × 3 each leg',
                        'Standing forward fold: 1 min, breathing deeply',
                        'PNF stretching (contract-relax) for faster gains',
                        'Don\'t bounce — slow and steady',
                    ],
                },
                {
                    id: 'thoracic-rotation',
                    number: '4.4',
                    title: 'Thoracic Rotation',
                    subtitle: 'A stiff thoracic spine = round shoulders + forward head + loss of height.',
                    icon: 'refresh-outline',
                    eta: '2 min',
                    bullets: [
                        'Open-book stretches: 10 reps each side',
                        'Quadruped thoracic rotation',
                        'Foam roller thoracic mobilization',
                        'Daily, focus on slow controlled rotation',
                    ],
                },
            ],
        },

        /* ── Ch 5 ──────────────────────────────────────────────────── */
        {
            id: 'training',
            number: 5,
            title: 'Strength Training For Height-Read',
            subtitle: 'Strong glutes, back, neck, traps = visible upright posture.',
            icon: 'barbell-outline',
            sections: [
                {
                    id: 'glute-strength',
                    number: '5.1',
                    title: 'Glute Strength',
                    subtitle: 'Strong glutes anchor the pelvis in neutral, not anterior tilt.',
                    icon: 'fitness-outline',
                    eta: '2 min',
                    bullets: [
                        'Hip thrusts: 3×8 heavy',
                        'Bulgarian split squats: 3×10 each leg',
                        'Glute bridges: 3×15 daily as activation',
                        'Strong glutes = neutral pelvis = taller standing',
                    ],
                },
                {
                    id: 'back-strength',
                    number: '5.2',
                    title: 'Upper Back Strength',
                    subtitle: 'Mid traps, rear delts, lats — the postural anchors.',
                    icon: 'expand-outline',
                    eta: '2 min',
                    bullets: [
                        'Face pulls: 3×15 at end of every push session',
                        'Reverse pec deck: 3×12',
                        'Chest-supported rows: 3×8–12',
                        'Pull-ups or pulldowns: lats keep shoulders square',
                    ],
                },
                {
                    id: 'neck-traps',
                    number: '5.3',
                    title: 'Neck & Traps',
                    subtitle: 'Weak neck on a tall body looks lopsided. Train both.',
                    icon: 'man-outline',
                    eta: '2 min',
                    bullets: [
                        'Neck curls + extensions: 2×15, 2×/week',
                        'Trap shrugs: 3×12–15',
                        'Trap raises: light, controlled',
                        'Stop if dizzy or numb',
                    ],
                },
                {
                    id: 'core',
                    number: '5.4',
                    title: 'Core For Posture',
                    subtitle: 'Stable core = pelvis doesn\'t tilt under loaded standing.',
                    icon: 'fitness-outline',
                    eta: '2 min',
                    bullets: [
                        'Planks: 60s × 3, slow build',
                        'Dead bugs: 10 each side',
                        'Hollow holds: 30s × 3',
                        'Avoid heavy crunches — boxy waist + no postural benefit',
                    ],
                },
            ],
        },

        /* ── Ch 6 ──────────────────────────────────────────────────── */
        {
            id: 'sleep-position',
            number: 6,
            title: 'Sleep & Position',
            subtitle: 'Sleep is the main spinal decompressor. Position matters.',
            icon: 'bed-outline',
            sections: [
                {
                    id: 'why-sleep',
                    number: '6.1',
                    title: 'Why Sleep Decompresses',
                    subtitle: '7–9 horizontal hours rehydrate your discs.',
                    icon: 'moon-outline',
                    eta: '2 min',
                    bullets: [
                        'Lying flat removes spinal compression',
                        'Discs reabsorb fluid and recover height',
                        'Morning measurement always taller',
                        '<6 h sleep = less recovery, less morning height',
                    ],
                },
                {
                    id: 'sleep-position',
                    number: '6.2',
                    title: 'Best Position',
                    subtitle: 'Back > side > stomach. Pillow choice matters.',
                    icon: 'bed-outline',
                    eta: '2 min',
                    bullets: [
                        'Back: most natural spinal alignment',
                        'Side: fine with proper pillow (head + neck aligned)',
                        'Stomach: rotates the cervical spine all night — worst',
                        'Pillow: thin enough to keep neck neutral',
                    ],
                },
                {
                    id: 'mattress',
                    number: '6.3',
                    title: 'Mattress',
                    subtitle: 'Medium-firm supports decompression best.',
                    icon: 'bed-outline',
                    eta: '1 min',
                    bullets: [
                        'Too soft: spine sags, no decompression',
                        'Too firm: pressure points + restless sleep',
                        'Medium-firm + good lumbar support is the sweet spot',
                        'Replace every 8–10 years',
                    ],
                },
                {
                    id: 'morning-protocol',
                    number: '6.4',
                    title: 'Morning Protocol',
                    subtitle: 'Hold your slept-in height with morning posture work.',
                    icon: 'sunny-outline',
                    eta: '1 min',
                    bullets: [
                        'Cobra pose 30s × 3 in bed',
                        'Stand: dead hang 30s × 2 if you have a bar',
                        'Wall posture hold 60s',
                        'Then get on with the day',
                    ],
                },
            ],
        },

        /* ── Ch 7 ──────────────────────────────────────────────────── */
        {
            id: 'footwear',
            number: 7,
            title: 'Footwear & Insoles',
            subtitle: 'The single biggest "honest" height add. Use it deliberately.',
            icon: 'walk-outline',
            sections: [
                {
                    id: 'shoe-stack',
                    number: '7.1',
                    title: 'Shoe Stack Heights',
                    subtitle: 'Different styles add different inches.',
                    icon: 'options-outline',
                    eta: '2 min',
                    bullets: [
                        'Sneakers (chunky / dad-shoe): +1.5–2 inches',
                        'Boots (Chelsea, work boots): +1–2 inches',
                        'Cuban-heel boots: +1.5–2.5 inches',
                        'Elevator shoes: +2–4 inches (visible if not chosen carefully)',
                    ],
                },
                {
                    id: 'insoles',
                    number: '7.2',
                    title: 'Insoles',
                    subtitle: 'Hidden boost for any shoe with enough room.',
                    icon: 'add-outline',
                    eta: '2 min',
                    bullets: [
                        'Heel-lift insoles: +1–2 inches discreet',
                        'Pair with high-collar boots so no edge shows',
                        'Comfortable for full-day wear if quality',
                        'Walk normally — exaggerated stride gives it away',
                    ],
                },
                {
                    id: 'styling-shoes',
                    number: '7.3',
                    title: 'Styling Shoes',
                    subtitle: 'Tiny shoes unbalance a developed upper body.',
                    icon: 'shirt-outline',
                    eta: '2 min',
                    bullets: [
                        'Slight platform sneakers (1–1.5 inches built-in)',
                        'Chunkier sneakers',
                        'Clean white sneakers',
                        'Boots with structure',
                    ],
                },
                {
                    id: 'pant-shoe-balance',
                    number: '7.4',
                    title: 'Pant + Shoe Balance',
                    subtitle: 'Hem length affects perceived leg length and total stack.',
                    icon: 'cut-outline',
                    eta: '1 min',
                    bullets: [
                        'Pant break covering shoe top: maximum leg-length read',
                        'Cropped pants kill leg length',
                        'Cuffs above the ankle = looks shorter',
                        'Same color pant + shoe = visually elongated',
                    ],
                },
            ],
        },

        /* ── Ch 8 ──────────────────────────────────────────────────── */
        {
            id: 'styling',
            number: 8,
            title: 'Clothing For Vertical Read',
            subtitle: 'Cuts, colors, and lines that make any frame look taller.',
            icon: 'shirt-outline',
            sections: [
                {
                    id: 'monochrome',
                    number: '8.1',
                    title: 'Monochrome Outfits',
                    subtitle: 'Same color top to bottom = unbroken vertical line.',
                    icon: 'color-palette-outline',
                    eta: '2 min',
                    bullets: [
                        'All-dark or all-light reads taller',
                        'Avoid sharp color contrast at the waist (cuts you in half)',
                        'Suit dressing: same-color jacket + trousers > contrasting',
                        'Even loungewear: matching set vs random pieces',
                    ],
                },
                {
                    id: 'fit',
                    number: '8.2',
                    title: 'Fit Rules',
                    subtitle: 'Loose hides height. Fitted reads taller. Tight is too far.',
                    icon: 'shirt-outline',
                    eta: '2 min',
                    bullets: [
                        'Fitted (not skinny) at the torso',
                        'Tapered (not skinny) pants',
                        'Sleeves end at wrist bone, never longer',
                        'Avoid oversized streetwear if heightmaxxing is the goal',
                    ],
                },
                {
                    id: 'lines',
                    number: '8.3',
                    title: 'Vertical Lines',
                    subtitle: 'Stripes, plackets, button-fronts — all read taller.',
                    icon: 'remove-outline',
                    eta: '1 min',
                    bullets: [
                        'Vertical stripes (subtle, not gaudy)',
                        'Open button-up over a tee creates vertical column',
                        'Long necklaces / pendant chains',
                        'V-necks open the upper body vertically',
                    ],
                },
                {
                    id: 'avoid',
                    number: '8.4',
                    title: 'What To Avoid',
                    subtitle: 'These cut you in half and shrink the visual frame.',
                    icon: 'close-circle-outline',
                    eta: '1 min',
                    bullets: [
                        'Wide horizontal stripes',
                        'Big belts that break the silhouette at the waist',
                        'Cropped jackets ending at the natural waist',
                        'High-contrast belts (cuts you visually)',
                    ],
                },
            ],
        },

        /* ── Ch 9 ──────────────────────────────────────────────────── */
        {
            id: 'hair-frame',
            number: 9,
            title: 'Hair & Frame',
            subtitle: 'The right haircut adds 0.5–1 inch of perceived height.',
            icon: 'cut-outline',
            sections: [
                {
                    id: 'volume-on-top',
                    number: '9.1',
                    title: 'Volume On Top',
                    subtitle: 'A taller silhouette starts above the eyebrows.',
                    icon: 'arrow-up-outline',
                    eta: '2 min',
                    bullets: [
                        'Quiff, pompadour, textured crop with height',
                        '+0.5–1 inch perceived height honestly',
                        'Use a matte clay for hold + lift',
                        'Blowdry up before styling',
                    ],
                },
                {
                    id: 'flat-sides',
                    number: '9.2',
                    title: 'Flat / Faded Sides',
                    subtitle: 'Slim sides + height on top = elongated head shape.',
                    icon: 'cut-outline',
                    eta: '1 min',
                    bullets: [
                        'Skin fade or low fade visually slims the head',
                        'Keeps focus on the height up top',
                        'Avoid wide-side cuts that balloon the head',
                    ],
                },
                {
                    id: 'beard-balance',
                    number: '9.3',
                    title: 'Beard Balance',
                    subtitle: 'Long beards shorten the face. Trimmed beards elongate.',
                    icon: 'man-outline',
                    eta: '1 min',
                    bullets: [
                        'Stubble or short beard: elongates the face',
                        'Long full beard: shortens the visual face length',
                        'Keep cheek line tight + neck shaved cleanly',
                    ],
                },
                {
                    id: 'avoid-hair',
                    number: '9.4',
                    title: 'What To Avoid',
                    subtitle: 'Cuts that shrink the perceived face/head.',
                    icon: 'close-circle-outline',
                    eta: '1 min',
                    bullets: [
                        'Long hair past shoulders (drops focus down)',
                        'Wide / mushroom cuts',
                        'Bowl cuts',
                        'Slicked-back if you have thin hair (shows scalp, kills volume)',
                    ],
                },
            ],
        },

        /* ── Ch 10 ─────────────────────────────────────────────────── */
        {
            id: 'photo',
            number: 10,
            title: 'Photo & Posing',
            subtitle: 'Camera height + posture = instant 1–2 inch perceived gain.',
            icon: 'camera-outline',
            sections: [
                {
                    id: 'camera-height',
                    number: '10.1',
                    title: 'Camera Height',
                    subtitle: 'Camera at chest height or below = looks taller. Above = looks shorter.',
                    icon: 'aperture-outline',
                    eta: '2 min',
                    bullets: [
                        'Camera at chest level: standard tall read',
                        'Camera at waist level: feels powerful',
                        'Camera above eye level: shrinks you visibly',
                        'Phone selfie at face level: neutral',
                    ],
                },
                {
                    id: 'posing-tall',
                    number: '10.2',
                    title: 'Pose For Tall',
                    subtitle: 'Crown reaching up, ribcage stacked, weight forward.',
                    icon: 'man-outline',
                    eta: '2 min',
                    bullets: [
                        'Crown of head reaching for the ceiling',
                        'Slight chest lift (not military-stiff)',
                        'Weight slightly forward on the balls of the feet',
                        'Slight contrapposto: one leg bent, one straight, hip out',
                    ],
                },
                {
                    id: 'group-photos',
                    number: '10.3',
                    title: 'Group Photos',
                    subtitle: 'Where you stand and how you position relative to others matters.',
                    icon: 'people-outline',
                    eta: '2 min',
                    bullets: [
                        'Stand on slightly higher ground if possible',
                        'Stand at the edge — shorter people closer to camera shrink you',
                        'Step back ~6 inches from the line — perspective adds height',
                        'Subtle weight forward + crown up',
                    ],
                },
                {
                    id: 'mirror-photos',
                    number: '10.4',
                    title: 'Mirror Photos',
                    subtitle: 'For physique / outfit shots — the angle is everything.',
                    icon: 'phone-portrait-outline',
                    eta: '1 min',
                    bullets: [
                        'Phone at chest level, slightly tilted up',
                        'Stand 4–6 feet from mirror',
                        'Crown reaching up, monochrome outfit',
                        'Avoid the bathroom-floor shot pointing up — fish-eye distortion',
                    ],
                },
            ],
        },

        /* ── Ch 11 ─────────────────────────────────────────────────── */
        {
            id: 'mistakes',
            number: 11,
            title: 'Common Mistakes',
            subtitle: 'The patterns that quietly steal your perceived height.',
            icon: 'alert-circle-outline',
            sections: [
                {
                    id: 'slumped-sitting',
                    number: '11.1',
                    title: 'Slumped Sitting',
                    subtitle: 'Sitting badly all day makes posture compensation impossible later.',
                    icon: 'remove-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Screen at eye level — non-negotiable',
                        'Hips above knees, back supported',
                        'Stand or walk every 30 min',
                        'Standing desk can help if you actually use it',
                    ],
                },
                {
                    id: 'wrong-pillow',
                    number: '11.2',
                    title: 'Wrong Pillow',
                    subtitle: 'Too thick or too thin = you wake up shorter and stiffer.',
                    icon: 'bed-outline',
                    eta: '1 min',
                    bullets: [
                        'Side sleeper: thicker pillow keeps neck neutral',
                        'Back sleeper: thin pillow only',
                        'Stomach sleeper: skip the pillow (and switch positions)',
                        'Replace every 1–2 years',
                    ],
                },
                {
                    id: 'over-decompression',
                    number: '11.3',
                    title: 'Over-Decompressing',
                    subtitle: 'Hanging for 20 minutes won\'t make you taller — just sore.',
                    icon: 'time-outline',
                    eta: '1 min',
                    bullets: [
                        'More hang time ≠ more height',
                        'Discs only rehydrate to a point',
                        'Stick to the protocol: 30s × 3, 1–2× daily',
                        'Excessive hanging strains shoulders and grip',
                    ],
                },
                {
                    id: 'cope-products',
                    number: '11.4',
                    title: 'Cope Products',
                    subtitle: 'Height-growth pills, "stretching machines," HGH stacks for adults.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'No supplement grows bone in adults — period',
                        '"Height growth pills" are scams',
                        'HGH for height in closed-plate adults: doesn\'t work',
                        'Limb-lengthening surgery is the only real bone gain in adults',
                    ],
                },
            ],
        },

        /* ── Ch 12 ─────────────────────────────────────────────────── */
        {
            id: 'build-stack',
            number: 12,
            title: 'Build Your Personal Stack',
            subtitle: 'Beginner / intermediate / advanced playbooks.',
            icon: 'construct-outline',
            sections: [
                {
                    id: 'beginner',
                    number: '12.1',
                    title: 'Beginner Stack',
                    subtitle: 'Three habits, no gear, 6 weeks to see real change.',
                    icon: 'medal-outline',
                    eta: '2 min',
                    bullets: [
                        'Wall posture hold: 60s, 1× daily',
                        'Chin tucks + thoracic extension: 5 min daily',
                        'Screen at eye level (raise it now)',
                        'Sleep 7–9 h, side or back',
                    ],
                },
                {
                    id: 'intermediate',
                    number: '12.2',
                    title: 'Intermediate Stack',
                    subtitle: 'Add training and decompression and footwear.',
                    icon: 'medal',
                    eta: '2 min',
                    bullets: [
                        'Continue beginner stack',
                        'Dead hangs: 30s × 3, 2× daily',
                        'Glute / rear delt / mid-trap training 2×/week',
                        'Switch to slight-platform sneakers as default',
                        'Hip flexor stretches: 60s each side, 2× daily',
                    ],
                },
                {
                    id: 'advanced',
                    number: '12.3',
                    title: 'Advanced Stack',
                    subtitle: 'Maximize honest perceived height + photo + styling.',
                    icon: 'trophy-outline',
                    eta: '2 min',
                    bullets: [
                        'Inversion table 5–10 min/evening',
                        'Hair: structured volume on top + skin fade sides',
                        'Outfit: monochrome by default, vertical lines',
                        'Photo discipline: camera at chest, crown reaching up',
                        'Heel-lift insoles for events',
                    ],
                },
                {
                    id: 'tracking',
                    number: '12.4',
                    title: 'Tracking',
                    subtitle: 'Measure same time of day, same posture, monthly.',
                    icon: 'analytics-outline',
                    eta: '1 min',
                    bullets: [
                        'Morning measurement against a doorframe',
                        'Same time, same posture, same shoes (or none)',
                        'Monthly photos: front, side, full-body',
                        'Realistic: 0.5–1 inch perceived gain in 12 weeks',
                    ],
                },
            ],
        },
    ],
};
