/**
 * SKINMAX course content. See ./courseContent.ts for the schema.
 */
import type { CourseModule } from './courseContent';

export const SKINMAX_COURSE: CourseModule = {
    maxxId: 'skinmax',
    accent: '#8B5CF6',
    accentSoft: 'rgba(139, 92, 246, 0.10)',
    accentMid: 'rgba(139, 92, 246, 0.20)',
    caption: '14 chapters · 64 lessons · built for newcomers',
    chapters: [
        /* ── Ch 1 ──────────────────────────────────────────────────── */
        {
            id: 'foundations',
            number: 1,
            title: 'Skin Foundations',
            subtitle: 'Start here. What skin is, what changes, what does not.',
            icon: 'leaf-outline',
            sections: [
                {
                    id: 'what-skin-is',
                    number: '1.1',
                    title: 'What Skin Actually Is',
                    subtitle: 'Three layers, one barrier, one job: keep things in and out.',
                    icon: 'layers-outline',
                    eta: '3 min',
                    bullets: [
                        'Epidermis: top, renews every 28 days',
                        'Dermis: collagen + elastin + blood supply',
                        'Hypodermis: fat layer, cushion + insulation',
                        'Stratum corneum is the working barrier you can affect',
                    ],
                    body:
                        'Most "skincare" actually targets the stratum corneum — the outermost dead-cell layer. ' +
                        'It renews itself every ~4 weeks. The dermis below holds collagen and elastin, which is ' +
                        'where long-term firmness and aging live; you affect it slowly via SPF and retinoids.',
                },
                {
                    id: 'type-vs-condition',
                    number: '1.2',
                    title: 'Type vs Condition',
                    subtitle: 'Type is genetic. Condition is what your skin is doing today.',
                    icon: 'analytics-outline',
                    eta: '2 min',
                    bullets: [
                        'Type: dry, oily, combination, normal — mostly fixed',
                        'Condition: dehydrated, sensitized, congested — temporary',
                        'You can be oily AND dehydrated (the most common mismatch)',
                        'Treat the condition first, then the type',
                    ],
                },
                {
                    id: 'four-layers',
                    number: '1.3',
                    title: 'Four Layers You Can Affect',
                    subtitle: 'Different products hit different depths. Match the tool to the job.',
                    icon: 'options-outline',
                    eta: '3 min',
                    bullets: [
                        'Surface (cleansing, exfoliation, gua sha)',
                        'Barrier (ceramides, niacinamide, occlusives)',
                        'Active reaching deeper layers (retinoids, AHAs, vitamin C)',
                        'Systemic (sleep, diet, sun exposure, hormones)',
                    ],
                },
                {
                    id: 'why-routines-fail',
                    number: '1.4',
                    title: 'Why Most Routines Fail',
                    subtitle: 'It is almost always too much, too fast, or too inconsistent.',
                    icon: 'warning-outline',
                    eta: '2 min',
                    bullets: [
                        'Stacking 5 actives on a barrier that is already broken',
                        'Switching products every 2 weeks before they can work',
                        'Skipping SPF — the only step that compounds',
                        'Chasing fad ingredients instead of the basics',
                    ],
                },
                {
                    id: 'realistic-timelines',
                    number: '1.5',
                    title: 'Realistic Timelines',
                    subtitle: 'Skin is slow. Set expectations or you will quit too early.',
                    icon: 'hourglass-outline',
                    eta: '2 min',
                    bullets: [
                        'Hydration: same day to 1 week',
                        'Acne: 6–12 weeks for new actives to settle',
                        'Pigmentation: 8–16 weeks visibly',
                        'Anti-aging from retinoids: 3–6 months minimum',
                    ],
                },
            ],
        },

        /* ── Ch 2 ──────────────────────────────────────────────────── */
        {
            id: 'reading-skin',
            number: 2,
            title: 'Reading Your Skin',
            subtitle: 'Diagnosis comes before any product purchase.',
            icon: 'eye-outline',
            sections: [
                {
                    id: 'find-skin-type',
                    number: '2.1',
                    title: 'Find Your Skin Type',
                    subtitle: 'The bare-skin 30-minute test is the most reliable home check.',
                    icon: 'water-outline',
                    eta: '2 min',
                    bullets: [
                        'Wash face, apply nothing, wait 30 minutes',
                        'Shiny T-zone, dry cheeks → combination',
                        'Tight all over → dry',
                        'Shiny everywhere → oily; comfortable everywhere → normal',
                    ],
                },
                {
                    id: 'identify-concerns',
                    number: '2.2',
                    title: 'Identify Your Concerns',
                    subtitle: 'Pick the top 1–2 that bother you most. Routines target concerns, not types.',
                    icon: 'list-outline',
                    eta: '3 min',
                    bullets: [
                        'Acne (comedones, inflammatory, hormonal)',
                        'Texture (rough, uneven, large pores)',
                        'Tone (dullness, hyperpigmentation, redness)',
                        'Aging (fine lines, sagging, sun damage)',
                        'Sensitivity (stinging, flushing, eczema)',
                    ],
                },
                {
                    id: 'spot-vs-systemic',
                    number: '2.3',
                    title: 'Spot vs Systemic',
                    subtitle: 'A patch is local. Whole-face flares come from inside.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Single spot: spot-treat, do not change whole routine',
                        'Whole-face acne flare: look at sleep, stress, diet, products',
                        'Cyclic monthly flare: hormonal — different protocol',
                        'Sudden new redness everywhere: ask "what changed in last 14 days?"',
                    ],
                },
                {
                    id: 'genetic-vs-lifestyle',
                    number: '2.4',
                    title: 'Genetic vs Lifestyle',
                    subtitle: 'Know what you can move and what you cannot.',
                    icon: 'git-branch-outline',
                    eta: '2 min',
                    bullets: [
                        'Genetic: pore size, undertone, oil baseline, scar tendency',
                        'Lifestyle-driven: hydration, dullness, mild breakouts, puffiness',
                        'Photodamage: half nature, half SPF habits since age 10',
                        'Aim energy at the lifestyle layer first — biggest ROI',
                    ],
                },
                {
                    id: 'when-derm',
                    number: '2.5',
                    title: 'When To See A Dermatologist',
                    subtitle: 'Some problems will not yield to the best home routine.',
                    icon: 'medical-outline',
                    eta: '2 min',
                    bullets: [
                        'Cystic or scarring acne — escalate, do not white-knuckle',
                        'Suspected rosacea, eczema flares, or persistent rashes',
                        'Pigmentation that has not moved in 3 months of consistent SPF + actives',
                        'Anything growing, changing color, or bleeding (mole check)',
                    ],
                },
            ],
        },

        /* ── Ch 3 ──────────────────────────────────────────────────── */
        {
            id: 'foundational-routine',
            number: 3,
            title: 'The Foundational Routine',
            subtitle: 'Before any active. Three steps, two times a day.',
            icon: 'sparkles-outline',
            sections: [
                {
                    id: 'three-step-min',
                    number: '3.1',
                    title: 'The 3-Step Minimum',
                    subtitle: 'Cleanse, moisturize, SPF. If you cannot do these, do not add anything else.',
                    icon: 'checkmark-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Cleanser: gentle, fragrance-free, no foam-monster sulfates',
                        'Moisturizer: ceramide or hyaluronic-acid based',
                        'SPF: 30+ broad-spectrum, every morning, every season',
                        'Master these for 4 weeks before adding actives',
                    ],
                },
                {
                    id: 'morning-framework',
                    number: '3.2',
                    title: 'Morning Routine',
                    subtitle: 'Light, defensive, fast.',
                    icon: 'sunny-outline',
                    eta: '2 min',
                    bullets: [
                        'Splash water or gentle cleanser (skip if very dry)',
                        'Vitamin C serum (optional, 2 weeks in)',
                        'Lightweight moisturizer',
                        'SPF 30–50 — the non-negotiable step',
                    ],
                },
                {
                    id: 'evening-framework',
                    number: '3.3',
                    title: 'Evening Routine',
                    subtitle: 'Cleanse properly, repair, treat.',
                    icon: 'moon-outline',
                    eta: '2 min',
                    bullets: [
                        'Cleanser (double-cleanse if you wore SPF or makeup)',
                        'Treatment serum or active (alternate nights)',
                        'Moisturizer; barrier cream if compromised',
                        'Optional: lip balm, eye cream',
                    ],
                },
                {
                    id: 'frequency-rules',
                    number: '3.4',
                    title: 'Frequency Rules',
                    subtitle: 'How often is more important than what brand.',
                    icon: 'repeat-outline',
                    eta: '2 min',
                    bullets: [
                        'Cleanser + moisturizer: 2× daily, every day',
                        'SPF: every morning, period',
                        'Retinoid: 2–3× per week, ramp slowly',
                        'Strong AHA/BHA: 1–3× per week max',
                    ],
                },
                {
                    id: 'order-of-ops',
                    number: '3.5',
                    title: 'Order Of Operations',
                    subtitle: 'Thinnest texture to thickest. Watery → creamy → oily.',
                    icon: 'swap-vertical-outline',
                    eta: '2 min',
                    bullets: [
                        'Cleanser → toner → essence → serum → cream → SPF (AM)',
                        'Cleanser → toner → treatment → serum → cream → balm (PM)',
                        'Wait 30–60 sec between layers if anything stings',
                        'SPF is always last in the AM, never under moisturizer',
                    ],
                },
            ],
        },

        /* ── Ch 4 ──────────────────────────────────────────────────── */
        {
            id: 'cleansing',
            number: 4,
            title: 'Cleansing',
            subtitle: 'Strip the right amount of oil. Never more.',
            icon: 'water-outline',
            sections: [
                {
                    id: 'what-cleansers-do',
                    number: '4.1',
                    title: 'What Cleansers Do',
                    subtitle: 'Surfactants surround oil and dirt so water can rinse them away.',
                    icon: 'fitness-outline',
                    eta: '2 min',
                    bullets: [
                        'Stripping cleansers leave skin "squeaky" — that is bad',
                        'Goal: clean but comfortable, no tightness',
                        'Bar soaps and sulfates strip too much for facial use',
                        'pH ~5.5 cleansers respect the acid mantle',
                    ],
                },
                {
                    id: 'choose-cleanser',
                    number: '4.2',
                    title: 'Choosing By Skin Type',
                    subtitle: 'Cream for dry. Gel for oily. Hydrating for sensitive.',
                    icon: 'options-outline',
                    eta: '3 min',
                    bullets: [
                        'Dry / mature: cream or oil-based cleanser',
                        'Oily / acne: low-foaming gel, salicylic acid optional 1–2× per week',
                        'Sensitive: micellar water or hydrating lotion cleanser',
                        'Combination: hydrating gel that does not over-strip',
                    ],
                },
                {
                    id: 'cleansing-technique',
                    number: '4.3',
                    title: 'Cleansing Technique',
                    subtitle: 'Lukewarm water, fingertips only, 30–60 seconds.',
                    icon: 'hand-left-outline',
                    eta: '2 min',
                    bullets: [
                        'Lukewarm — hot water dehydrates and triggers redness',
                        'Use fingertips, never a brush or rough cloth',
                        'Massage 30–60 seconds; that is when surfactants work',
                        'Rinse thoroughly, pat dry — never rub with a towel',
                    ],
                },
                {
                    id: 'double-cleanse',
                    number: '4.4',
                    title: 'Double-Cleanse',
                    subtitle: 'Oil first, then water. Only when you wore SPF or makeup.',
                    icon: 'duplicate-outline',
                    eta: '2 min',
                    bullets: [
                        'Step 1: oil or balm cleanser dissolves SPF/makeup',
                        'Step 2: gentle water-based cleanser rinses residue',
                        'Skip the morning double-cleanse — it is overkill',
                        'Skip on bare-skin nights too — strips the barrier',
                    ],
                },
                {
                    id: 'cleansing-mistakes',
                    number: '4.5',
                    title: 'What NOT To Cleanse With',
                    subtitle: 'These wreck the barrier and you will spend months rebuilding it.',
                    icon: 'close-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Bar soap (too alkaline)',
                        'Hot water (dehydrates, triggers flushing)',
                        'Cleansing brushes daily (mechanical irritation)',
                        'Witch hazel pads with alcohol (for "oily" skin — backfires)',
                    ],
                },
            ],
        },

        /* ── Ch 5 ──────────────────────────────────────────────────── */
        {
            id: 'moisturizing',
            number: 5,
            title: 'Moisturizing',
            subtitle: 'Lock water in, reinforce the barrier nightly.',
            icon: 'cloud-outline',
            sections: [
                {
                    id: 'humectant-emollient-occlusive',
                    number: '5.1',
                    title: 'The Three Ingredient Types',
                    subtitle: 'Humectants pull water in. Emollients smooth. Occlusives seal.',
                    icon: 'beaker-outline',
                    eta: '3 min',
                    bullets: [
                        'Humectants: hyaluronic acid, glycerin, urea, panthenol',
                        'Emollients: squalane, jojoba oil, fatty acids, cholesterol',
                        'Occlusives: petrolatum, dimethicone, lanolin, beeswax',
                        'A good moisturizer has all three',
                    ],
                },
                {
                    id: 'pick-by-type',
                    number: '5.2',
                    title: 'Pick By Skin Type',
                    subtitle: 'Match texture to skin needs.',
                    icon: 'options-outline',
                    eta: '2 min',
                    bullets: [
                        'Dry: rich cream with ceramides + occlusives',
                        'Oily: lightweight gel-cream, fragrance-free',
                        'Sensitive: minimalist barrier cream — fewer ingredients',
                        'Mature: ceramide cream + peptides + niacinamide',
                    ],
                },
                {
                    id: 'damp-skin',
                    number: '5.3',
                    title: 'Apply On Damp Skin',
                    subtitle: 'Damp skin holds humectants. Dry skin loses them to the air.',
                    icon: 'water-outline',
                    eta: '1 min',
                    bullets: [
                        'Pat — do not towel-dry — after cleansing',
                        'Apply moisturizer within 60 seconds',
                        'A spritz of plain water or hydrating toner works too',
                        'Especially critical with hyaluronic acid serums',
                    ],
                },
                {
                    id: 'slugging',
                    number: '5.4',
                    title: 'Slugging',
                    subtitle: 'A thin layer of petrolatum locks everything in. PM only.',
                    icon: 'shield-checkmark-outline',
                    eta: '3 min',
                    bullets: [
                        'Last step at night, over moisturizer',
                        'Tiny amount — pea-sized for the whole face',
                        'Skip on retinoid or acid nights (occludes too much)',
                        'Best for compromised barriers or dry climates',
                    ],
                },
                {
                    id: 'moisture-mistakes',
                    number: '5.5',
                    title: 'Mistakes To Avoid',
                    subtitle: 'Common ways the moisturizing step backfires.',
                    icon: 'alert-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Skipping it because skin is "oily" (worsens the oil cycle)',
                        'Applying after SPF — undoes the SPF',
                        'Using a heavy occlusive while breaking out — clogs',
                        'Switching every 3 weeks before it works',
                    ],
                },
            ],
        },

        /* ── Ch 6 ──────────────────────────────────────────────────── */
        {
            id: 'sun-protection',
            number: 6,
            title: 'Sun Protection',
            subtitle: 'The single highest-leverage habit you can build.',
            icon: 'sunny-outline',
            sections: [
                {
                    id: 'why-spf',
                    number: '6.1',
                    title: 'Why SPF Beats Everything',
                    subtitle: 'UV is the #1 driver of aging, pigmentation, and visible damage.',
                    icon: 'flash-outline',
                    eta: '3 min',
                    bullets: [
                        'UVA penetrates clouds, glass, and aging your dermis daily',
                        'Daily SPF 30 outperforms most $300 anti-aging serums',
                        'Pigmentation always returns without SPF — even if you fade it',
                        'Skipping SPF undoes every other product in your stack',
                    ],
                },
                {
                    id: 'mineral-vs-chemical',
                    number: '6.2',
                    title: 'Mineral vs Chemical',
                    subtitle: 'Two valid approaches with different feels and tradeoffs.',
                    icon: 'swap-horizontal-outline',
                    eta: '3 min',
                    bullets: [
                        'Mineral (zinc, titanium): physical block, gentler, can leave white cast',
                        'Chemical: invisible, more elegant, can sting sensitive skin',
                        'Hybrid formulas (EltaMD UV Clear) combine both',
                        'Best SPF = the one you will actually wear',
                    ],
                },
                {
                    id: 'two-finger',
                    number: '6.3',
                    title: 'How Much To Apply',
                    subtitle: 'The two-finger rule. Most people use 1/3 the protection they think.',
                    icon: 'finger-print-outline',
                    eta: '2 min',
                    bullets: [
                        'Two finger-lengths of SPF for face + neck',
                        '1/4 teaspoon for face alone is the lab dose',
                        'Under-applying drops SPF 50 to roughly SPF 15',
                        'Apply 15 minutes before sun exposure',
                    ],
                },
                {
                    id: 'reapply',
                    number: '6.4',
                    title: 'Reapplication',
                    subtitle: 'Every 2 hours outdoors. Powder or stick over makeup.',
                    icon: 'refresh-outline',
                    eta: '2 min',
                    bullets: [
                        'Reapply every 2 hours when actively outside',
                        'After swimming, sweating, or towel-drying',
                        'Powder SPF over makeup — quick top-up',
                        'Indoors with no window light: morning application enough',
                    ],
                },
                {
                    id: 'spf-myths',
                    number: '6.5',
                    title: 'Common SPF Myths',
                    subtitle: 'The misinformation that keeps people from wearing it.',
                    icon: 'help-circle-outline',
                    eta: '2 min',
                    bullets: [
                        '"Dark skin doesn\'t need SPF" — false; PIH is worse without it',
                        '"Clouds block UV" — UVA passes through 80% of cloud cover',
                        '"My moisturizer has SPF" — usually under-applied, not enough',
                        '"SPF prevents vitamin D" — incidental sun on hands/arms is plenty',
                    ],
                },
            ],
        },

        /* ── Ch 7 ──────────────────────────────────────────────────── */
        {
            id: 'actives',
            number: 7,
            title: 'Actives — The Power Tools',
            subtitle: 'Where real results compound. Add slowly, layer carefully.',
            icon: 'flask-outline',
            sections: [
                {
                    id: 'vitamin-c',
                    number: '7.1',
                    title: 'Vitamin C',
                    subtitle: 'Antioxidant defense by day. Brightens over months.',
                    icon: 'sunny-outline',
                    eta: '3 min',
                    bullets: [
                        'L-ascorbic acid 10–20% is the gold standard',
                        'AM only, before SPF, on cleansed skin',
                        'Fades pigmentation over 8–12 weeks of consistent use',
                        'Store in a cool, dark place — oxidizes when brown',
                    ],
                },
                {
                    id: 'niacinamide',
                    number: '7.2',
                    title: 'Niacinamide',
                    subtitle: 'The well-tolerated workhorse: sebum, pores, barrier, redness.',
                    icon: 'flower-outline',
                    eta: '3 min',
                    bullets: [
                        '5–10% concentration is plenty',
                        'Plays well with almost everything (no fight with C)',
                        'Reduces sebum and pore appearance over 4–8 weeks',
                        'Helps barrier repair — useful during retinoid ramp-up',
                    ],
                },
                {
                    id: 'retinoids',
                    number: '7.3',
                    title: 'Retinoids',
                    subtitle: 'The single best-studied anti-aging + acne ingredient.',
                    icon: 'sparkles-outline',
                    eta: '4 min',
                    bullets: [
                        'OTC: adapalene 0.1% (Differin) — best entry retinoid',
                        'Stronger: tretinoin 0.025–0.1% — needs prescription',
                        'Start 2× per week, ramp to nightly over 8 weeks',
                        'PM only, pea-size for whole face, always with SPF next AM',
                    ],
                    body:
                        'Retinoids accelerate cell turnover, build collagen, and unclog pores. They are the ' +
                        'anti-aging gold standard with decades of evidence. Expect a "purge" of small bumps in ' +
                        'weeks 2–6 — that is normal and resolves. Never combine same-night with strong AHAs/BHAs.',
                },
                {
                    id: 'ahas',
                    number: '7.4',
                    title: 'AHAs',
                    subtitle: 'Glycolic, lactic, mandelic. Surface texture and tone.',
                    icon: 'apps-outline',
                    eta: '3 min',
                    bullets: [
                        'Glycolic: smallest molecule, deepest, can irritate',
                        'Lactic: hydrating bonus, gentler entry AHA',
                        'Mandelic: largest molecule, gentlest, good for darker skin',
                        '1–2× per week max; never on retinoid nights',
                    ],
                },
                {
                    id: 'bhas',
                    number: '7.5',
                    title: 'BHAs',
                    subtitle: 'Salicylic acid. Goes inside the pore — ideal for blackheads.',
                    icon: 'ellipse-outline',
                    eta: '2 min',
                    bullets: [
                        'Salicylic acid 1–2% is the sweet spot',
                        'Oil-soluble — penetrates sebum, cleans pores from inside',
                        'Best for oily, acne-prone, blackhead-prone skin',
                        'Use 2–3× per week, AM or PM, never with strong AHAs same day',
                    ],
                },
                {
                    id: 'azelaic',
                    number: '7.6',
                    title: 'Azelaic Acid',
                    subtitle: 'Underrated. Redness, PIH, mild acne. Pregnancy-safe.',
                    icon: 'leaf-outline',
                    eta: '2 min',
                    bullets: [
                        '10% OTC, 15–20% prescription',
                        'Reduces redness and post-inflammatory hyperpigmentation',
                        'Anti-microbial action helps inflammatory acne',
                        'Layers safely with most things, including retinoids',
                    ],
                },
                {
                    id: 'layering',
                    number: '7.7',
                    title: 'Layering Rules',
                    subtitle: 'What plays nice. What fights. What burns the barrier.',
                    icon: 'git-merge-outline',
                    eta: '3 min',
                    bullets: [
                        'Vitamin C (AM) + retinoid (PM): great pair',
                        'Retinoid + AHA same night: avoid (unless very tolerant)',
                        'Niacinamide pairs with everything safely',
                        'Benzoyl peroxide deactivates retinol — separate AM/PM',
                    ],
                },
                {
                    id: 'tolerance',
                    number: '7.8',
                    title: 'Build Tolerance',
                    subtitle: 'Start low, go slow. Sandwich with moisturizer if irritated.',
                    icon: 'trending-up-outline',
                    eta: '3 min',
                    bullets: [
                        'New active: 2× per week for 2 weeks, then 3×, then 4×, etc.',
                        'Sandwich method: moisturizer → active → moisturizer',
                        'Stop and rebuild barrier if stinging or peeling persists',
                        'Patch-test on inner forearm before face for sensitive skin',
                    ],
                },
            ],
        },

        /* ── Ch 8 ──────────────────────────────────────────────────── */
        {
            id: 'acne',
            number: 8,
            title: 'Acne Protocol',
            subtitle: 'Different acne types, different protocols. Match the cause.',
            icon: 'medkit-outline',
            sections: [
                {
                    id: 'acne-types',
                    number: '8.1',
                    title: 'Types Of Acne',
                    subtitle: 'Comedonal, inflammatory, hormonal, cystic — each treats differently.',
                    icon: 'list-outline',
                    eta: '3 min',
                    bullets: [
                        'Comedonal: blackheads, whiteheads — retinoid + BHA',
                        'Inflammatory: red papules/pustules — BPO + niacinamide',
                        'Hormonal: chin/jaw cycle flare — see derm for spironolactone',
                        'Cystic: deep, painful, scarring — escalate to derm fast',
                    ],
                },
                {
                    id: 'otc-stack',
                    number: '8.2',
                    title: 'The OTC Stack',
                    subtitle: 'What works for most adult acne without a prescription.',
                    icon: 'briefcase-outline',
                    eta: '4 min',
                    bullets: [
                        'AM: gentle cleanser → niacinamide 10% → moisturizer → SPF 30+',
                        'PM: cleanser → adapalene 0.1% → moisturizer',
                        'BHA 2× per week (separate from retinoid nights)',
                        'Spot treat with benzoyl peroxide 2.5% only on active spots',
                    ],
                },
                {
                    id: 'spot-treat',
                    number: '8.3',
                    title: 'Spot Treatments',
                    subtitle: 'Local actives for individual spots. Do not use everywhere.',
                    icon: 'locate-outline',
                    eta: '2 min',
                    bullets: [
                        'Benzoyl peroxide 2.5%: kills C. acnes bacteria',
                        'Hydrocolloid patches: pull pus, prevent picking',
                        'Sulfur 5–10%: dries down a single inflamed spot',
                        'Tea tree oil: weak but tolerated; use diluted',
                    ],
                },
                {
                    id: 'diet-lifestyle',
                    number: '8.4',
                    title: 'Diet & Lifestyle',
                    subtitle: 'Real triggers exist but they are individual. Track patterns.',
                    icon: 'restaurant-outline',
                    eta: '3 min',
                    bullets: [
                        'High-glycemic spikes correlate with acne in some people',
                        'Whey protein triggers acne in a subset of users',
                        'Dairy correlation is real but not universal',
                        'Sleep deprivation and stress reliably worsen flares',
                    ],
                },
                {
                    id: 'when-to-escalate',
                    number: '8.5',
                    title: 'When To Escalate',
                    subtitle: 'Some acne needs a prescription. Do not white-knuckle.',
                    icon: 'arrow-up-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'No improvement after 12 weeks of consistent OTC stack',
                        'Cystic, painful, or scarring lesions',
                        'Suspected hormonal acne (cyclic, jaw/chin)',
                        'Mental-health impact — not a failure to ask for help',
                    ],
                },
            ],
        },

        /* ── Ch 9 ──────────────────────────────────────────────────── */
        {
            id: 'anti-aging',
            number: 9,
            title: 'Anti-Aging & Long-Term',
            subtitle: 'Prevention beats reversal. The compound interest of skincare.',
            icon: 'time-outline',
            sections: [
                {
                    id: 'what-aging-means',
                    number: '9.1',
                    title: 'What Aging Skin Means',
                    subtitle: 'Two clocks: chronological and photo-aging. SPF controls one.',
                    icon: 'hourglass-outline',
                    eta: '2 min',
                    bullets: [
                        'Intrinsic: collagen drops ~1% per year after age 25',
                        'Extrinsic (photo): UV damage, often 80% of visible aging',
                        'Glycation: sugar binds collagen, stiffens skin',
                        'Free-radical damage: cumulative, antioxidant-defendable',
                    ],
                },
                {
                    id: 'prevention-stack',
                    number: '9.2',
                    title: 'The Prevention Stack',
                    subtitle: 'SPF + retinoid is the only combo with strong long-term evidence.',
                    icon: 'shield-checkmark-outline',
                    eta: '3 min',
                    bullets: [
                        'Daily SPF 30+ from teens onward',
                        'Tretinoin or adapalene nightly from late 20s',
                        'Vitamin C AM for antioxidant support',
                        'Sleep and stress management — collagen needs recovery',
                    ],
                },
                {
                    id: 'antioxidants',
                    number: '9.3',
                    title: 'Daily Antioxidants',
                    subtitle: 'Neutralize free radicals before they damage collagen.',
                    icon: 'flash-outline',
                    eta: '2 min',
                    bullets: [
                        'Vitamin C (topical) — best-studied',
                        'Vitamin E pairs with C, extends potency',
                        'Ferulic acid stabilizes the C+E combo',
                        'Resveratrol, niacinamide — supportive role',
                    ],
                },
                {
                    id: 'peptides',
                    number: '9.4',
                    title: 'Peptides — Useful Or Hype?',
                    subtitle: 'Some are evidence-backed. Most marketing is overblown.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Matrixyl (palmitoyl pentapeptide-4): real collagen support',
                        'Copper peptides: wound healing + collagen, mid evidence',
                        'Argireline: marketed as Botox-like — weak in vivo data',
                        'Use as a supplement, never a retinoid replacement',
                    ],
                },
                {
                    id: 'realistic-aging',
                    number: '9.5',
                    title: 'Realistic Expectations',
                    subtitle: 'Skincare buys time. It does not reverse 20 years overnight.',
                    icon: 'trending-up-outline',
                    eta: '2 min',
                    bullets: [
                        'Tretinoin: visible firmness change in 6–12 months',
                        'Pigmentation fading: 8–16 weeks consistent application',
                        'Deep wrinkles: in-office (lasers, fillers) needed for big changes',
                        'Genetics + sun history set the ceiling — habits set the floor',
                    ],
                },
            ],
        },

        /* ── Ch 10 ─────────────────────────────────────────────────── */
        {
            id: 'special-concerns',
            number: 10,
            title: 'Special Concerns',
            subtitle: 'Targeted protocols for the most common stubborn problems.',
            icon: 'compass-outline',
            sections: [
                {
                    id: 'pigmentation',
                    number: '10.1',
                    title: 'Hyperpigmentation',
                    subtitle: 'Sun spots, melasma, post-acne marks. SPF + actives + patience.',
                    icon: 'contrast-outline',
                    eta: '3 min',
                    bullets: [
                        'SPF 50 every day — without it nothing else works',
                        'Vitamin C AM, azelaic acid 10% PM',
                        'Tretinoin or adapalene PM for stubborn cases',
                        'Hydroquinone 4% (Rx) for short courses under derm guidance',
                    ],
                },
                {
                    id: 'redness-rosacea',
                    number: '10.2',
                    title: 'Redness & Rosacea',
                    subtitle: 'Calm the trigger. Avoid the actives that make it worse.',
                    icon: 'thermometer-outline',
                    eta: '3 min',
                    bullets: [
                        'Identify triggers: heat, alcohol, spicy food, sun',
                        'Azelaic acid 15% (Rx) is first-line for rosacea',
                        'Mineral SPF + ceramide cream baseline',
                        'Avoid: fragrance, menthol, alcohol-based toners, harsh exfoliants',
                    ],
                },
                {
                    id: 'eczema-sensitive',
                    number: '10.3',
                    title: 'Eczema & Sensitive Skin',
                    subtitle: 'Restore the barrier first. Strip the routine to the basics.',
                    icon: 'snow-outline',
                    eta: '3 min',
                    bullets: [
                        'Cut the routine to: gentle cleanser + ceramide cream + mineral SPF',
                        'Avoid fragrance, essential oils, sulfates, alcohol',
                        'Petrolatum or Cicaplast for active flares',
                        'Topical steroid 1% hydrocortisone for short flare control',
                    ],
                },
                {
                    id: 'hormonal',
                    number: '10.4',
                    title: 'Hormonal Flares',
                    subtitle: 'Cyclic acne, oil shifts. Bigger picture than topical alone.',
                    icon: 'pulse-outline',
                    eta: '3 min',
                    bullets: [
                        'Track flare timing across cycle — confirms hormonal pattern',
                        'OCPs and spironolactone are first-line Rx for women',
                        'Inositol (myo + d-chiro) for PCOS-driven acne',
                        'Topical: niacinamide + adapalene + spot BPO',
                    ],
                },
                {
                    id: 'scarring',
                    number: '10.5',
                    title: 'Scarring',
                    subtitle: 'Most "scars" are PIH/PIE (color). True scarring is texture.',
                    icon: 'medical-outline',
                    eta: '3 min',
                    bullets: [
                        'PIH (brown): vitamin C + azelaic + tretinoin + SPF',
                        'PIE (red): time + niacinamide + SPF; consider in-office laser',
                        'Atrophic scars (texture): microneedling, lasers, subcision',
                        'Stop picking — every pick adds 3+ months to fade time',
                    ],
                },
            ],
        },

        /* ── Ch 11 ─────────────────────────────────────────────────── */
        {
            id: 'debloat',
            number: 11,
            title: 'Debloat & Same-Day Glow',
            subtitle: 'Tactical face improvements for tomorrow morning.',
            icon: 'snow-outline',
            sections: [
                {
                    id: 'why-puffy',
                    number: '11.1',
                    title: 'Why Faces Puff',
                    subtitle: 'Sodium, alcohol, sleep, allergies, hormones, fluid pooling.',
                    icon: 'water-outline',
                    eta: '2 min',
                    bullets: [
                        'High sodium dinner — face holds water 12–16 hours',
                        'Alcohol disrupts deep sleep + dehydrates',
                        'Allergies puff under-eyes via histamine',
                        'Lying flat lets fluid pool — head-elevated sleep helps',
                    ],
                },
                {
                    id: 'cold-protocol',
                    number: '11.2',
                    title: 'Cold Splash Protocol',
                    subtitle: 'The cheapest, fastest face fix. Constricts and drains.',
                    icon: 'thermometer-outline',
                    eta: '2 min',
                    bullets: [
                        'Ice-cold water splash 30–60 seconds, mornings',
                        'Cold metal roller works similarly — 2 minutes',
                        'Skip if you have rosacea or visible flushing tendency',
                        'Use cold caffeine eye serum after for under-eyes',
                    ],
                },
                {
                    id: 'photo-prep',
                    number: '11.3',
                    title: 'Pre-Photo 24h Prep',
                    subtitle: 'When you need to look your best on a specific day.',
                    icon: 'camera-outline',
                    eta: '3 min',
                    bullets: [
                        'Cap sodium under 2g for the day',
                        'No alcohol; avoid late-night high-carb dinner',
                        '8+ hours sleep, head elevated',
                        'Morning: cold splash → light gua sha → caffeine serum → walk',
                    ],
                },
                {
                    id: 'diet-sleep',
                    number: '11.4',
                    title: 'Diet & Sleep Tactics',
                    subtitle: 'Long-game inputs that compound visibly over weeks.',
                    icon: 'bed-outline',
                    eta: '2 min',
                    bullets: [
                        '2–3 L water/day baseline — counterintuitive, but cuts retention',
                        'Cut processed sodium spikes (chips, fast food)',
                        'Antihistamine if you have chronic allergic puffiness',
                        '7–9 hours sleep at consistent times',
                    ],
                },
                {
                    id: 'lymph-massage',
                    number: '11.5',
                    title: 'Lymphatic Massage',
                    subtitle: 'Gentle drainage. Light pressure only — never aggressive scraping.',
                    icon: 'hand-left-outline',
                    eta: '3 min',
                    bullets: [
                        'Drain DOWN: cheek → ear → neck → collarbone',
                        'Use a slip product (oil or moisturizer)',
                        'Light pressure — no lasting redness',
                        '2–3 minutes, 3–5× per week, never on inflamed skin',
                    ],
                },
            ],
        },

        /* ── Ch 12 ─────────────────────────────────────────────────── */
        {
            id: 'lifestyle',
            number: 12,
            title: 'Lifestyle Factors',
            subtitle: 'Habits that move skin more than any product.',
            icon: 'sunny-outline',
            sections: [
                {
                    id: 'sleep-master',
                    number: '12.1',
                    title: 'Sleep — Master Variable',
                    subtitle: 'Bad sleep is visible on the face within 24 hours.',
                    icon: 'moon-outline',
                    eta: '3 min',
                    bullets: [
                        '7–9 hours, consistent window',
                        'Skin barrier repair peaks in second half of night',
                        'Cortisol from short sleep → puffiness, breakouts',
                        'Cool dark room, phone outside if possible',
                    ],
                },
                {
                    id: 'diet-inflammation',
                    number: '12.2',
                    title: 'Diet & Inflammation',
                    subtitle: 'Whole-food, lower-glycemic eating helps inflammatory skin.',
                    icon: 'restaurant-outline',
                    eta: '3 min',
                    bullets: [
                        'High-glycemic + dairy correlate with acne in many studies',
                        'Omega-3s (fatty fish, walnuts) reduce inflammation',
                        'Vegetables + whole grains feed gut — skin reflects gut',
                        'Track for 4 weeks if you suspect a trigger food',
                    ],
                },
                {
                    id: 'stress',
                    number: '12.3',
                    title: 'Stress & Cortisol',
                    subtitle: 'Chronic stress = chronic inflammation = chronic flare.',
                    icon: 'pulse-outline',
                    eta: '2 min',
                    bullets: [
                        'Cortisol drives sebum and inflammation',
                        'Walking, daylight exposure, social contact help',
                        'Meditation/breathing has small but real effect',
                        'Therapy and treatment for ongoing stress are skin care too',
                    ],
                },
                {
                    id: 'workouts-sweat',
                    number: '12.4',
                    title: 'Workouts & Sweat',
                    subtitle: 'Sweat helps. Sweating in dirty makeup or hat-bands does not.',
                    icon: 'barbell-outline',
                    eta: '2 min',
                    bullets: [
                        'Cleanse fully before workouts (no SPF/makeup left)',
                        'Wash within 30 minutes after sweating',
                        'Wash hats, helmet pads, headbands weekly',
                        'Resistance training raises GH, supports skin recovery',
                    ],
                },
                {
                    id: 'hydration',
                    number: '12.5',
                    title: 'Hydration Reality',
                    subtitle: 'Drink water, but it does not "plump" skin like serums do.',
                    icon: 'water-outline',
                    eta: '2 min',
                    bullets: [
                        '2–3 L water/day baseline — more if active or hot climate',
                        'Topical hydration (humectants + moisturizer) does the visible work',
                        'Caffeine and alcohol are mildly diuretic — offset with water',
                        'Electrolytes if heavy sweating — sodium + potassium balance',
                    ],
                },
            ],
        },

        /* ── Ch 13 ─────────────────────────────────────────────────── */
        {
            id: 'mistakes',
            number: 13,
            title: 'Common Mistakes',
            subtitle: 'The patterns that quietly wreck most newcomer routines.',
            icon: 'alert-circle-outline',
            sections: [
                {
                    id: 'over-exfoliate',
                    number: '13.1',
                    title: 'Over-Exfoliating',
                    subtitle: 'The most common newbie mistake. Symptoms look like the problem.',
                    icon: 'remove-circle-outline',
                    eta: '2 min',
                    bullets: [
                        'Stinging, redness, tightness after exfoliation = stop',
                        'Limit AHAs/BHAs to 2× per week initially',
                        'No physical scrubs daily',
                        'Rebuild for 4–6 weeks with bland routine if barrier is broken',
                    ],
                },
                {
                    id: 'too-many-actives',
                    number: '13.2',
                    title: 'Stacking Too Many Actives',
                    subtitle: 'More is not more. Three actives is plenty for most skin.',
                    icon: 'layers-outline',
                    eta: '2 min',
                    bullets: [
                        'Pick: 1 antioxidant (AM), 1 retinoid (PM), 1 niacinamide (any)',
                        'Add a 4th only after 8 weeks of stable tolerance',
                        'New active alone — never stack two new products in same week',
                        'When irritated: remove actives, return to 3-step minimum',
                    ],
                },
                {
                    id: 'product-swapping',
                    number: '13.3',
                    title: 'Switching Too Fast',
                    subtitle: 'Products need 8–12 weeks to show their real effect.',
                    icon: 'swap-horizontal-outline',
                    eta: '2 min',
                    bullets: [
                        'Cleanser/moisturizer: 2 weeks min before judging',
                        'Active serums: 8–12 weeks for fair test',
                        'Retinoids: 6 months before "this does not work for me"',
                        'Track results photographically every 4 weeks',
                    ],
                },
                {
                    id: 'skipping-spf',
                    number: '13.4',
                    title: 'Skipping SPF',
                    subtitle: 'The single act that undoes everything else in your routine.',
                    icon: 'sunny-outline',
                    eta: '1 min',
                    bullets: [
                        'Skipping SPF cancels your retinoid investment',
                        'Pigmentation always comes back without it',
                        'Even indoors near windows — UVA passes through glass',
                        'Find one you genuinely like to wear, then wear it',
                    ],
                },
                {
                    id: 'picking',
                    number: '13.5',
                    title: 'Picking & Touching',
                    subtitle: 'Hands carry bacteria. Picking adds months to a single spot.',
                    icon: 'hand-right-outline',
                    eta: '2 min',
                    bullets: [
                        'Every pick = 2–6 weeks of pigmentation',
                        'Hydrocolloid patches on active spots — kills the urge',
                        'Hands off the face — touching transfers bacteria',
                        'Phone screens against the face = more breakouts on that side',
                    ],
                },
            ],
        },

        /* ── Ch 14 ─────────────────────────────────────────────────── */
        {
            id: 'building-stack',
            number: 14,
            title: 'Build Your Personal Stack',
            subtitle: 'Decision framework + concrete starter, mid, and advanced stacks.',
            icon: 'construct-outline',
            sections: [
                {
                    id: 'decision-framework',
                    number: '14.1',
                    title: 'Decision Framework',
                    subtitle: 'Three questions before adding any product.',
                    icon: 'help-circle-outline',
                    eta: '3 min',
                    bullets: [
                        '1. What concern does this solve that I actually have?',
                        '2. Have I given my current routine 8 weeks?',
                        '3. Will I actually use it nightly for 3 months?',
                        'If you can\'t answer all three, skip the purchase',
                    ],
                },
                {
                    id: 'beginner-stack',
                    number: '14.2',
                    title: 'Beginner Stack',
                    subtitle: 'Under $50. Three products. Run for 8 weeks before adding anything.',
                    icon: 'medal-outline',
                    eta: '3 min',
                    bullets: [
                        'CeraVe Hydrating Cleanser (~$15)',
                        'CeraVe PM Lotion (~$17)',
                        'EltaMD UV Clear SPF 46 (~$40) — or any SPF 30+ you like',
                        'That is the entire stack. Use it for 60 days.',
                    ],
                },
                {
                    id: 'intermediate-stack',
                    number: '14.3',
                    title: 'Intermediate Stack',
                    subtitle: 'After 8 weeks of clean basics, layer in actives.',
                    icon: 'medal',
                    eta: '3 min',
                    bullets: [
                        'AM: cleanser → vitamin C (The Ordinary 10%) → moisturizer → SPF',
                        'PM: cleanser → adapalene 0.1% (M/W/F) → moisturizer',
                        'Niacinamide 10% can slot in any time (T/Th)',
                        'Run this for 12 weeks before considering anything else',
                    ],
                },
                {
                    id: 'advanced-stack',
                    number: '14.4',
                    title: 'Advanced Stack',
                    subtitle: 'For experienced skin only. Layered actives, cycled correctly.',
                    icon: 'trophy-outline',
                    eta: '4 min',
                    bullets: [
                        'AM: cleanser → vitamin C 15–20% → niacinamide → moisturizer → SPF 50',
                        'PM (5×/week): cleanser → tretinoin 0.025–0.05% → moisturizer',
                        'PM (2×/week): cleanser → BHA or AHA → moisturizer (off retinoid nights)',
                        'Azelaic 10% slot for redness/PIH days',
                    ],
                },
                {
                    id: 'tracking',
                    number: '14.5',
                    title: 'Tracking Results',
                    subtitle: 'Photos every 4 weeks. Same lighting, same angle, no makeup.',
                    icon: 'image-outline',
                    eta: '2 min',
                    bullets: [
                        'Weekly photos — bare skin, same window light, same angle',
                        'Monthly comparison: progress is invisible day-to-day',
                        'Note any new product start dates — correlate with flares',
                        'Patience over panic — most "this is not working" calls are wrong',
                    ],
                },
            ],
        },
    ],
};
